docs/math/fermat.md

&emsp;&emsp;添加了费马小定理和欧拉定理的基本内容及其证明。
&emsp;&emsp;需要添加一些数论的预备知识。

feat: update fermat

---

static/disqus.html

update commenting systems

---

docs/data-structure/advanced/seg-in-seg.md
docs/data-structure/intermediate/treap.md

And a minor C++ code highlight fix.

feat: update treap

---

docs/data-structure/advanced/balanced-in-seg.md

feat: add balanced-in-seg.md

---

docs/introduction/faq.md

merge .github/CONTRIBUTING.md into faq.md

---

docs/index.md
mkdocs.yml

set title to OI Wiki
better SEO

modify title of index page

---

static/disqus.html

closes https://github.com/Ir1d/gitment/issues/20
(we are now using customized gitment
edited from https://www.kymjs.com/qiniu/static/js/gitment.js.

fix: fix comments

---

.github/CONTRIBUTING.md
build.sh
docs/_static/css/extra.css
docs/_static/js/extra.js
docs/index.md
docs/introduction/faq.md
mkdocs.yml
static/disqus.html

feat: enable words counting and LICENSE statement inside pages

---

build.sh
docs/_static/js/extra.js
docs/index.md
mkdocs.yml

#169 .
jinja2 要求这个变量名是小写的才会起作用= =

 fix: fix pagetime display settings and word counting

---

docs/intro/resources.md

Update the href of [Judge Duck Online]

---

docs/string/sam.md

quick fix after quick reading.

---

docs/intro/faq.md

add pencil icon to faq.md

---

docs/ds/persistent-seg.md

提供了可持久化线段树的讲解

---

docs/graph/mst.md

Add Problems

---

docs/ds/dsu.md

我有强迫症所以做了些小修改

---

docs/math/mobius.md

fix: fix formula display

---

mkdocs.yml

fix: fix name

---

docs/math/linear-equation.md

。。。。修改了一下链接

---

mkdocs.yml

dumplicate with https://github.com/24OI/OI-wiki/blob/master/mkdocs.yml#L165

fix dumplicate

---

docs/intro/faq.md

update: faq.md

---

mkdocs.yml

change 「贝祖定理」 to 「裴蜀定理」 according to votes.

---

build.sh
docs/_static/js/extra.js
mkdocs.yml
static/disqus.html
static/footer.html

feat: use InstantClick

---

docs/_static/js/extra.js

Delete: Page-Time

---

mkdocs.yml

update js version

---

docs/math/bit.md

delete unexpected space on 79G

delete unexpected space

---

docs/string/sam.md

fix equation in HTML, fix missing itemize.

---

build.sh
docs/_static/js/extra.js
docs/intro/faq.md
mkdocs.yml
static/disqus.html
static/extra.js
static/footer.html
static/main.html

因为是 hard-code 了域名，所以 netlify 上看不到效果，我截个图
closes #312

feat: 在页面下方提供更多信息

---

docs/intro/faq.md

竟然不宣传 HtC……那要 HtC 有何用？
至少也是 **常见错误 & 不规范表达 合集**。

add tips refer to HtC; add more punctuations

---

mkdocs.yml

Thx to @wangyisong1996 :smile:

feat: add link for license

---

README.md

鸣谢 @HXLLL 提供脚本来统计 :+1: 
```python
import re
with open('nav.yml', 'r', encoding='utf-8') as sitemap:
with open('schedule.md', 'w', encoding='utf-8') as schedule:
for line in sitemap.readlines():
res = re.match(r'(^.*?- )(.*?:) ?(.*?$)', line)
if not res:
continue
if not res.group(3):
schedule.write(res.group(1) + res.group(2) + '\n')
else:
f = open('docs/'+res.group(3), 'r', encoding = 'utf-8')
s = res.group(1)
if len(f.read()) < 10:
s = s + '[ ] '
else:
s = s + '[x] '
s = s + res.group(2) + ' ' + res.group(3)
f.close()
schedule.write(s + '\n')
```

doc: update progress

---

.travis.yml
BaiduPusher.sh
Sitemap_Parser.py

加入了百度推送代码。     
设定了两个环境变量 **site** 和 **token**  ，请在travis端设置一下。    
临时加入到script里看看travis的效果，请删除后再merge。

Add BaiduPusher

---

docs/math/euler.md
docs/math/sieve.md

update: euler.md & sieve.md

---

docs/dp/backpack.md

fix fix fix

---

docs/misc/mo-algo.md

fix fomula & brackets

---

README.md
docs/index.md

Add Discord

---

docs/math/fft.md

fix: fix typo

---

docs/intro/wsl.md

style: fix format

---

.travis.yml
netlify_build.sh
render_math.js

（不好意思调试了很久，打扰大家了
我最近换了 zsh，忘记有些地方和 bash 不一样了 :new_moon_with_face: 
upd: :new_moon_with_face: 跑一遍要 8 min 了，似乎海星

fix: update render_math.js

---

docs/intro/resources.md

Ref: add OJ resource [DMOJ]

---

docs/string/sam.md

ref: https://github.com/e-maxx-eng/e-maxx-eng/pull/312/

fix: fix code

---

.travis.yml
scripts/BaiduPusher.sh
scripts/Sitemap_Parser.py

BaiduPusher:Bug fix

---

docs/graph/tree-misc.md

改善代码格式（适当增加空格）

---

docs/math/fermat.md

更改扩展欧拉公式的格式

---

docs/graph/scc.md

交换 Kosaraju、Tarjan 算法的顺序（将较常用的 Tarjan 挪到前面）

---

scripts/netlify_build.sh

Fix:Render_math.js

---

.travis.yml
README.md

fix: fix mirror of gh-pages branch

---

docs/math/sieve.md

修正 Issue #668

---

docs/graph/mst.md

Fix: bad link

---

docs/math/matrix.md

把循环边界统一为 sz 而非常数 3

---

.bashrc
Dockerfile

feat: docker deploy

---

docs/intro/editors.md

Update editors.md (Add VS Code)

---

docs/_static/css/han.css
mkdocs.yml

fix: remove text-align overcontrol of han.css

---

docs/_static/css/extra.css

style: 尝试让标题更显眼

---

mkdocs.yml

折叠了目录中的数学部分

---

docs/_static/css/extra.css
mkdocs.yml

fix: fix css selector

---

docs/basic/binary.md

update page status

---

mkdocs.yml

feat: support math fences

---

mkdocs.yml

chore: change title for pbds/priority-queue

---

.travis.yml

so travis stops once non-zero is met

ci: set -e for script

---

README.md

更改README部署方面的说法

---

gulpfile.js
package-lock.json
package.json

fix: remove imagemin

---

mkdocs.yml

delete duplicate word in site desc

---

docs/index.md

Sync title with README

---

README.md

好像这样也行，不知道哪种更好？
```
[![asciicast](https://asciinema.org/a/SlLiVHYv7kS2u2px18rUUDZep.svg)](https://asciinema.org/a/SlLiVHYv7kS2u2px18rUUDZep)
```
[![asciicast](https://asciinema.org/a/SlLiVHYv7kS2u2px18rUUDZep.svg)](https://asciinema.org/a/SlLiVHYv7kS2u2px18rUUDZep)
感觉应该找个 `@oi-wiki.org` 的重新录一下 :thinking:

feat: add asciinema

---

docs/basic/prefix-sum.md

Upd 前缀和&差分

---

docs/ds/persistent-balanced.md

修改可持久化平衡树 练手题

---

docs/ds/virtual-tree.md

Fix Format

---

docs/intro/judgers.md

Judgers.md -> Lemon

---

docs/ds/splay.md

fix: splay.md

---

docs/ds/segment.md

fix: Update segment.md

---

docs/math/prime.md

isPrime:  `n < 2`全部返回1是甚麼鬼
millerRabin: `n < 3`會導致SIGFPE(((

fix all prime check fns

---

docs/math/du-sieves.md

补充杜教筛的定义和例题，并微调了整篇文章的章节格式
添加一道杜教筛例题

补充杜教筛的定义和例题

---

docs/math/poly-sqrt.md

fix code in poly-sqrt.md

---

docs/intro/resources.md

added more resources

---

docs/dp/optimization.md

fix optimization.md

---

mkdocs.yml
scripts/build.sh
static/disqus.html
static/footer.html

主要是挪到了jsDelivr，`css.net`备案掉了后太慢了     
附本机ping图：

对网页的CDN做了一些更改

---

README.md
docs/math/bignum.md

Revert "Update bignum.md"

---

docs/dp/memo.md

去除代码中一个丑陋的全角分号

---

docs/graph/tree-hash.md
mkdocs.yml

[WIP] add 树哈希

---

docs/graph/flow.md
docs/graph/flow/min-cost.md
docs/graph/flow/min-cut.md

更正放反的最小割和费用流，将网络流24题移至简介

---

docs/intro/resources.md

* 修改排版
* 新增部分资源
* 改善图书类内容
感谢 PR ，请注明有意义 commit MSG & PR head ，勿滥用 PR 。我已阅读常见问题并处理：
- 半角空格；中文全角符号与英文不需要。
- 外链图片和引用链接问题， LaTex 公式问题，空行，目录双倍， NOI 系列规范名称（如 CTS）

:pen: Update resources.md

---

docs/basic/enumerate.md

should visit if the additive inverse of a[i] exist ???

may be an error need correct

---

docs/math/mobius.md

add problem links

---

mkdocs.yml

fix cdn (#1177)

---

docs/ds/pb-ds/priority-queue.md

fix: 二项堆描述的一个错误

---

mkdocs.yml

feat: init parallel binary search(整体二分)

---

docs/search/astar.md

修正因大写导致的404

---

docs/graph/tree-misc.md

bugfix of `son[v] - 1`

---

docs/intro/resources.md

adding NOJ

---

docs/graph/lca.md

Add LCA & Tarjan introduction

---

docs/ds/splay.md

update splay.md problem

---

docs/math/prime.md

修复#1251 没修好的锅
```diff
int main() {
-  while (scanf("%d", &n) != EOF) {
+  while (scanf("%lld", &n) != EOF) {
ans = INF;
dfs(0, 1, 1, 64);
-    printf("%d\n", ans);
+    printf("%lld\n", ans);
}
return 0;
}
```

chore: %lld -> %llu

---

docs/intro/resources.md

Lutece is the online judge system of UESTC.

Add Lutece

---

docs/basic/prefix-sum.md

feat: 增加高维前缀和

---

docs/ds/persistent-trie.md
docs/math/du-sieves.md

修复了有些地方出现了注解框，但下面的内容没有被折叠的问题。
------

修复部分内容未被折叠的问题

---

crowdin.yml

try crowdin for Translation

---

docs/_static/css/extra.css
mkdocs.yml
package-lock.json

marked as draft beacuse we are waiting for the mkdocs-material to be updated.
waiting for https://github.com/OI-wiki/mkdocs-material/pull/16
closes #1290, #1292 
- 删掉 han.css & js
- 删掉 extra.css 中影响标题的部分

 fix: remove han.css, bump mkdocs-material version

---

docs/graph/mst.md

用搜索找到了并查集与图的存储

---

docs/ds/binary-heap.md

Fix: [持续接锅]二插堆：更正代码缩进为4个空格

---

docs/dp/index.md

Fix mistake in DP

---

docs/ds/leftist-tree.md

Fix leftist tree: double \mathrm

---

mkdocs.yml

更新 平衡树 分类为 二叉搜索树&平衡树

---

docs/ds/segment-tree-beats.md

fix：线段树与区间历史最值：修正代码中的双##问题

---

docs/math/euler.md
docs/math/fermat.md

e-maxx的欧拉函数内容OI-wiki上都有了，所以只把习题搬一下QAQ

添加欧拉定理（函数）习题（搬运e-maxx习题

---

docs/math/fermat.md
gulpfile.js

fix: enable conservativeCollapse

---

docs/ds/heap.md

* [ x] 请务必确保您的文档中引用的**外链**图片已经全部转存到了**本库内**对应的`images`文件夹中（防止触发某些网站的防盗链），并已全部处理成了`MD文档名称+编号`的形式（可参考已有文档中图片的处理方式）  
* [ x] 请确保您的文档中的引用链接的稳定性，**不推荐**引用**自建**服务（如OJ）中的资源（如题目）
* [ x] 对于 LaTeX 公式，请注意常见的问题，**一定要使用** `$\log$`、`$\min$`、`$\max$`、`$\gcd$` 等，而非 `$log$`、`$min$`、`$max$`、`$gcd$`。对于最小公倍数，请使用 `$\operatorname{lcm}$` 而非 `$lcm$`，省略号请使用 `$\cdots$`，叉乘请使用 `$\times$`，点乘请使用 `$\cdot$`。
* [ x] 所有公式中的希腊字母等特殊符号，请不要使用输入法的插入特殊符号功能，而应该使用对应的 LaTeX 公式符号。如 phi 大多数情况下应该使用 `$\varphi$` 而不是 `$\phi$`。
* [x ] 行间公式前后各要有一行空行。
* [ x] 对于目录中存在公式的情况，请使用 HTML …

Fix a formula

---

docs/basic/prefix-sum.md

Add some exercises and code

---

mkdocs.yml
static/extra.js

closes #1403 
首先，十分感谢您花钱来给 OI Wiki 开一个 Pull Request，下面是付款须知：
- 请在付款的时候写比较有意义的备注

update extra.js according to #1403

---

docs/math/bsgs.md

1. 原文涉及过多原根方面知识，由于[OI-wiki的原根](https://oi-wiki.org/math/primitive-root/)已包含，因此移除冗余内容
2. 公式全写行内看着就心累，于是把部分公式改为行间公式
3. 合并e-maxx相关内容到此文
4. 进阶篇新增算法二，在结尾给出代码（e-maxx搬运
5. 重写EX-BSGS，写得更具体
6. 添加习题

update: 更新 BSGS 算法

---

docs/ds/index.md

倍增已经从数据结构中移出去了，目录里的倍增就删掉啦QAQ
------

删除数据结构简介中的“倍增”

---

docs/search/idastar.md

Better Indentation

---

docs/misc/io.md

首先，十分感谢你花钱来给 OI Wiki 开一个 Pull Request，下面是一些你可能需要知道的 PR 须知：  
- 请在 PR 的时候多给一点钱  
- 请给 PR 的款项起比较有意义的标题。   
- 关于同一类尚未合并的 PR 请直接在对应的页面中加钱，除非已有的钱数已抵达上限，否则**不要多开 PR**。

fix: 修正错误的模板表述

---

docs/math/catalan.md

修复 @Ir1d 昨天23:59在群里喊人pr修复的"Calalan"

fix: Catalan

---

docs/intro/oj-tool.md

**审核的同学** 请着重关注以下三方面：
1. 注意有没有 typo

Add Codeforces Visualizer in oj tool

---

docs/misc/complexity.md

fix(complexity): 修复排版混乱的公式

---

docs/intro/editor/vscode.md

fix(vscode): 补充配置要点

---

docs/math/poly/intro.md

在 [「多项式部分简介」](https://oi-wiki.org/math/poly/intro/) 一文中,有一处微小的LaTeX错误, 已在本pr中修正

修复intro.md(多项式部分简介)中小的LaTeX错误

---

mkdocs.yml

(mkdocs.yml) Google Analytics

---

docs/lang/helloworld.md

fix(helloworld): 删除多余的反引号

---

docs/math/sieve.md

fix: 修复不规范的循环写法

---

docs/intro/latex.md

mj 无法通过 `\^ e` 生成带音调的 e，因此换一种方法
将 lshort 的网址指向 OI-wiki/libs 仓库
1. 注意有没有 typo

fix(LaTeX): workround for mathjax

---

docs/math/permutation-group.md

bug fixed in permutation-group.md

---

docs/dp/index.md

1. 注意有没有 typo
参见issue：
https://github.com/OI-wiki/OI-wiki/issues/1584

修复”动态规划部分简介“中的错别字

---

docs/dp/index.md

1. 注意有没有 typo
修改内容：
将ans初始值修改为1
参见https://github.com/OI-wiki/OI-wiki/issues/1587

修改：动态规划部分简介-最长不下降子序列-解法一-ans初始值

---

docs/topic/rmq.md

修复 Four Russian 部分的复杂度公式

---

.github/pull_request_template.md

在 pr 模板中要求写上 fix 的 issue

---

docs/intro/wsl.md

修复【延伸内容】中【Dev on Windows with WSL】的链接。
1. 注意有没有 typo

Update wsl.md 更新链接

---

docs/intro/resources.md

迁移公告参考 [ZOJ 首页](http://acm.zju.edu.cn/onlinejudge/)
1. 注意有没有 typo

update zoj link in resources.md

---

docs/graph/bfs.md

fix: remove an excess right parenthesis

---

docs/graph/hld.md

fix：修正树链剖分伪代码格式

---

docs/search/idastar.md

Correct a wrong link to the problem (UVa1343).
1. 注意有没有 typo

Update idastar.md-Correct a wrong link to the problem (UVa1343).

---

docs/graph/scc.md

fix Kosaraju implement
1. 注意有没有 typo

fix Kosaraju implement

---

docs/ds/divide-combine.md

析合树模板查询传参错误

---

mkdocs.yml

（ddp 的 pr 是谁审的.webp）
1. 注意有没有 typo

add ddp in mkdocs.yml

---

docs/intro/faq.md

由于上游 GoogleHosts 对 Github 进行了一次更新 https://github.com/googlehosts/hosts/commit/22db3c1777a5c100230554fb379d12e0dfe15737  
故对项目中的Hosts进行更新
1. 注意项目地址是否可以访问
2. 注意hosts是否可用
3. 注意我是否打错了字

fix: update hosts

---

docs/ds/sparse-table.md

`[Warning] unused variable 'a' [-Wunused-variable]`
**审核的同学** 请着重关注以下一方面：
1. 自己康康这个变量有没有用
2. 有用的话请关闭这个 pr 并喷我

fix(ST): delete unused variable 'a'

---

docs/dp/dynamic.md

fix: 修改动态 dp 页面中的公式 typo

---

docs/graph/lgv.md
mkdocs.yml

add LGV lemma

---

docs/math/vector.md

**审核的同学** 请着重关注以下方面：
1. 注意有没有暴力字符串替换导致的锅

fix(vector): 修正向量字体为粗斜体

---

docs/intro/editor/eclipse.md

小改Eclipse食用指北

---

docs/lang/csl/iterator.md

原来的例子感觉并不是很好...换了一个 rbegin 来解释
1. 注意有没有 typo

:bug: fix(iter): 修复对 rend 的错误解释

---

docs/intro/wsl.md

原文章竟然出现了五级标题（
把标题层级稍微调整了一下，使之更合逻辑。
1. 注意有没有 typo

fix(wsl): correct heading leval

---

docs/geometry/convex-hull.md

凸包：fix typo

---

docs/intro/resources.md

Update the descriptions of a few OJ systems

---

docs/math/mobius.md

\RightArrow 应为 \implies
\LeftRightArrow 应为 \iff
1. 注意有没有 typo

:bug: fix(mobius): 修复了错误的“推出”与“等价”符号

---

docs/ds/leftist-tree.md

fix comments & links in leftist-tree

---

docs/intro/judgers.md

Project Ownership Transfer to oi-archive

---

docs/dp/opt/monotonous-queue-stack.md
docs/dp/opt/quadrangle.md
docs/graph/flow/bound.md

#1747 好像忘记搜索二级目录了...导致放在里面的没有改。
1. 注意有没有 typo

change luogu to loj

---

docs/intro/resources.md

Add links to open-source OJ projects

---

docs/math/inverse.md

Change a wrong link from LOJ 152 to LOJ 161 and change a link from Luogu P3811 to LOJ 110.
1. 注意有没有 typo

Update inverse.md - Change two links

---

docs/misc/io.md

之前的板子在读入字符串时遇到 EOF 会挂..（模拟赛时使用发现的。）
1. 注意有没有 typo

fix fast io template

---

docs/geometry/distance.md

修复一个距离公式的typo

---

docs/misc/frac-programming.md

fix(frac-programming): fix typo

---

docs/_static/js/extra.js
docs/edit-landing.md
docs/intro/faq.md
mkdocs.yml

fix #1821 
注：感觉调用 Github API 局限颇多，日后可以考虑自建一套 API
1. 注意有没有 typo

修正 api 调用地址，简化编辑流程

---

README.md

可能 README 里面还需要 rephrase，不过先这样好像也海星啦～

添加 FeatHub

---

docs/intro/faq.md

fix(docs/intro/faq): fix hosts

---

docs/math/crt.md

Update crt.md - Correct a mistake
Change ``(ans + m * b) mod n → ans``  to ``(ans + a[i] * m * b) mod n → ans``
1. 注意有没有 typo

Update crt.md - Correct a mistake

---

docs/ds/stack.md

style(stack): 删除了 :: 周围的空格

---

README.md

Revert "添加 FeatHub"

---

docs/misc/gray-code.md

Update gray-code.md, add CSP S2 2019 D1T1 as refered problem. 

---

docs/intro/editor/emacs.md

Update emacs.md 这个bot怎么把我的details搞没了

---

docs/graph/hld.md

目前给的代码编译不了，fix这个编译问题，跑出正确结果。
另外，我个人对树这里有一个问题，文档中有的时候是“结点”，有的时候是“节点”，到底应该是哪一种？是不是应该保持一致？我发现国内的一些题目也都还不一致。理论上数据结构中的jiedian都应该是“结点”，对吧？

Fix code bug in HLD

---

docs/dp/knapsack.md

fix miss typing

---

docs/misc/cc-basic.md

fix(cc-basic): typo

---

docs/ds/kdt.md

avx->vax,这里应该使用方差来比较
1. 注意有没有 typo

Update kdt.md 修改代码错误

---

docs/string/kmp.md

修正了前缀函数部分的一个下标的typo。
1. 注意有没有 typo

修正了前缀函数部分的一个typo

---

docs/math/poly/div-mod.md

fix (poly):typo

---

docs/math/poly/multipoint-eval-interpolation.md

原本该部分提到的 O(nlog^3n) 复杂度的算法已经明显过时，故将该部分方法叙述改为现流行的 O(nlog^2n) 复杂度的算法
1. 注意有没有 typo

修改多项式多点插值部分

---

docs/intro/resources.md

补充了一本算法竞赛书和两个 Codeforces 社区高质量算法文章合集

---

mkdocs.yml

Happy New Year!

---

docs/basic/bubble-sort.md

增加冒泡排序起始索引的说明

---

docs/math/mobius.md

原来性质部分的叙述应该属于莫比乌斯函数的定义，着重证明的应该是 $\sum_{d\mid n}\mu(d)=\varepsilon(n)$ 这一性质
1. 注意有没有 typo

修正莫比乌斯函数的定义以及性质

---

docs/intro/resources.md

add hzwer/sharePPT

---

docs/graph/dfs.md

修复一个dfs伪码typo

---

docs/math/bsgs.md

有些地方 mod 错误地打成了 \bmod 或者 \mod，统一修正为 \pmod。
1. 注意有没有 typo

修了 BSGS 中的公式问题

---

docs/math/gcd.md

1. 修复最大/最小值角标
2. 更改符号避免歧义
1. 注意有没有 typo

fix equation in gcd.md

---

docs/math/du.md

du(math): put codeblock into notes

---

docs/math/bsgs.md

修正一些 LaTeX 问题

---

.travis.yml
README.md

update coding repo url

---

docs/ds/dsu.md

因为不是所有的人都能使用英文维基
1. 注意有没有 typo

添加关于 Ackermann 函数的内容

---

docs/math/newton.md

这里的newton代码有个优先级的小问题，加个括号就更加清晰了。
1. 注意有没有 typo

Fix small issue in newton code

---

README.md

fix: 修改 README 中的字符画

---

docs/dp/dynamic.md

ddp:put codeblock into details

---

docs/_redirects

add _redirects file for netlify

---

.travis.yml
scripts/gen_redirect.py

gen redirect conf for nginx

---

docs/intro/faq.md
docs/intro/htc.md
scripts/gen_redirect.py

closes #2017 
如有 suggestion，欢迎直接 edit（
1. 注意有没有 typo

add docs for _redirects

---

docs/intro/judgers.md

更新评测工具 Lemon 的维护状态
添加了 iotang 维护的 Lemon fork

更新评测工具 Lemon 的维护状态

---

docs/geometry/half-plane.md
docs/math/basis.md

修改一处很神奇的代码

---

docs/intro/resources.md

将文本中的 LaTeX 更改为直体

---

docs/intro/spj.md

RT，同时增加了一个写 SPJ 的注意事项。
1. 注意有没有 typo

add: 添加 DOMJudge 的 spj 和 testlib 相关内容

---

docs/geometry/inverse.md

fix the index error on line 29

---

docs/intro/resources.md

add some books

---

docs/basic/construction.md

fix link error

---

docs/ds/splay.md

fix #1958.
大概就是有些地方应该执行 splay 操作的地方都没有 splay，这个 pr 修的就是这样的锅。
1. 注意有没有 typo

修了 splay 中的一些锅

---

.github/ISSUE_TEMPLATE/config.yml

feat: add issue template

---

.travis.yml
README.md

Coding -> Gitee

---

docs/intro/faq.md
docs/intro/htc.md

将 FAQ 中关于如何贡献的内容移动到了 htc

---

.gitpod.yml
README.md

添加了 gitpod

---

docs/ds/lct.md

修复 LCT 代码中的一些 bug

---

docs/lang/csl/container-adapter.md

Fix 代码中Queue初始化使用了stack

---

docs/math/bsgs.md

修复bsgs进阶篇-找到所有解里混乱的变量名

---

docs/graph/scc.md

补上了 Kosaraju 代码中的一个分号
1. 注意有没有 typo

Update scc.md 补上了 Kosaraju 代码中的一个分号

---

docs/graph/scc.md

style(强连通分量): 修改代码风格

---

docs/math/matrix.md

Update matrix.md 矩阵乘法的板子打错了一个字符

---

docs/ds/sgt.md

修改替罪羊树表述错误

---

docs/ds/linked-list.md

- Remove an unnecessary assignment
- Add a reference to let changes on `p` take effect outside the function
- Free the `Node` after deletion to avoid potential memory leak
Thanks for the help of @TechCiel and @mcfxmcfx.
1. 注意有没有 typo

fix(ds): link-list.md

---

docs/math/bit.md

`__builtin_clrsb` 我觉得需要有人帮一下忙，我解释不清楚。
clang 好像也有，不过文档没找到，先不写上去。
---
1. 注意有没有 typo

改了一下内建函数部分

---

docs/math/poly/fwt.md

修改FWT中公式错误

---

docs/math/bsgs.md

Fix a spelling mistake

---

docs/ds/seg.md

修了线段树注释中的一个 typo

---

docs/math/crt.md

修复CRT的typo

---

docs/lang/python.md

Add npm.taobao.org to download Python.
1. 注意有没有 typo

添加一个 python 镜像站链接

---

docs/lang/python.md

Add Tutorial for Python

---

docs/lang/python.md

add Python Docs

---

docs/lang/python.md

Fix #2209: add typing check for Python tutorial

---

docs/lang/java.md

fix(docs/lang/java): fix error in output section and lint code

---

docs/intro/resources.md

添加了一些 BZOJ 相关内容。
1. 注意有没有 typo

添加了一些 BZOJ 相关内容。

---

docs/ds/sgt.md

修改替罪羊树代码中的注释错误

---

docs/ds/splay.md

由于 BZOJ 现在不支持 https ，故原有链接不能访问。
1. 注意有没有 typo

大视野不支持 https 了，更改了 Splay 中练习题的链接

---

README.md

添加summer 2020传送门
1. 注意有没有 typo

Add propaganda for summer2020

---

docs/intro/spj.md

(Work in progress) 简介/Special Judge

Refactor 6.5 (spj.md) 对页面进行格式化

---

docs/math/matrix.md

fix: Fix some wrong operators and delete some codes

---

docs/math/sieve.md

证明了埃氏筛法的复杂度

---

docs/index.md
docs/manifest.webmanifest
mkdocs.yml

1. 注意有没有 typo
----
Under the approval of @Ir1d, the npm packages `oicdn` has been published for deliver static files through jsDelivr.
According to the `jsDelivr ToS`, any files that are not violating the ToS of npm & github will be fine  to deliver through jsDelivr, thus the usage of the jsDelivr in this PR will not be considered as abuse.
Also, the MathJax hosted on `cdnjs.loli.net` has been changed to `cdn.jsdelivr.net` as well, as 
the ICP License for `loli.net` is no longer valid and the China CDN for `cdnjs.loli.net` has been removed accordingly.

perf: load static files from jsdelivr

---

docs/math/mobius.md

修改了 Dirichlet 卷积例子中的错误

---

docs/intro/oi.md

Fix typo in docs/intro/oi.md

---

docs/misc/io.md

「你们这什么 wiki 啊，你们害人不浅啊你们，随便一翻都是 bug」（（
1. 注意有没有 typo

fix typo in docs/misc/io.md

---

scripts/build.sh

perf(build): remove mathjax for production build

---

docs/lang/csl/algorithm.md

cc https://github.com/OI-wiki/gitment/issues/354#issuecomment-626140576
1. 注意有没有 typo

添加了关于 random_shuffle 的一些内容

---

docs/intro/faq.md
docs/intro/htc.md
docs/intro/resources.md
docs/intro/wsl.md
docs/lang/editor/vim.md

1. 注意有没有 typo
----
Small typos fix: `Github -> GitHub`.

fix: typo Github -> GitHub

---

docs/_static/css/extra.css

1. 注意有没有 typo
----
This PR attempts to implement a fix for #2321.
Closes #2321

fix(#2321): add overflow for mjpage container

---

docs/index.md
docs/manifest.webmanifest

1. 注意有没有 typo
----
Crop `netlify.png` from `1838x500` into `919x250` (`177KiB => 14.7KiB`).
Compress `favicon_512x512.png` (`3.73KiB => 2.88KiB`).

perf: optmize image

---

docs/misc/random.md

参数3应为myrand而不是myrand()。
1. 注意有没有 typo

std::shuffle声明笔误

---

docs/intro/roadmap.md
docs/math/expectation.md

添加了条件概率的内容

---

mkdocs.yml

更改线段树和树状数组的顺序

---

docs/math/poly/div-mod.md

反转时 x 替换为 1/x

---

docs/intro/latex.md

抱歉审核 #2341 的时候没仔细注意有没有 typo 0.0
1. 注意有没有 typo

fix typo in latex.md

---

docs/basic/divide-and-conquer.md

fix(divide-and-conquer): add author

---

docs/math/prime.md

add two vital '=' and a crucial '0'.
1. 注意有没有 typo

typo fix: in example function isPrime

---

Dockerfile
docs/intro/about.md
docs/intro/common-tricks.md
docs/intro/faq.md
docs/intro/htc.md
docs/string/sa.md
package.json

另外 line 27-29 都 88% 进度了还说『大部分都是空的』合适吗（
1. 注意有没有 typo

Update OI Wiki repo link

---

docs/math/integral.md
docs/math/quad-residue.md

1.对略去的证明部分进行了添加.
2.原先的return fl + fr - (fl + fr - ans) / 15;这一行似乎不太对,在进行数据测试以及比对其他模板后改成了return fl + fr + (fl + fr - ans) / 15;
3.添加了一些例题.
1. 注意有没有 typo

完善了数值积分的内容

---

docs/string/sa.md

更新后缀数组中的部分代码

---

docs/math/mobius.md

补全mobius章节相关证明+修改部分细节

---

README.md
docs/math/matrix.md

remove summer2020

---

docs/string/general-sam.md

补充了广义后缀自动机的内容

---

docs/topic/graph-matching/graph-match.md

Update links in graph-match.md

---

docs/string/general-sam.md

修正了页面上的一些显示错误，以及站内链接的更改

---

README.md

修改了 Telegram 和 QQ 的 badge，让它们更有识别度

[docs] 稍微美化一下 README 页的 badge

---

docs/ds/dividing.md

- `ds/dividing.md`
close #2449 
1. 注意有没有 typo

Fix typo in ds/dividing

---

docs/math/mobius.md

1. 补充了完全积性函数
2. 补充说明了狄利克雷卷积的运算规律
1. 注意有没有 typo

完善了 莫比乌斯反演 的内容

---

docs/lang/editor/eclipse.md

> 请不要让诸如「五级标题」这种事情再次发生了，一篇正常的文章是用不到如此复杂的结构层次的。
1. 注意有没有 typo

fix(eclipse): fix format

---

docs/lang/pas-cpp.md

fix(pas-cpp): update editor

---

docs/string/lyndon.md

fix: format and give better translation in string/Lyndon

---

docs/intro/format.md

添加了对多个字母组成的变量的格式要求

---

docs/string/basic.md

更正字符串基础中的小错误

---

docs/math/stirling.md

refactor stirling.md

---

docs/graph/2-sat.md

增加了2-SAT输出一个可行解的例题

---

docs/math/mobius.md

feat: 二维数论分块

---

docs/ds/decompose.md

Fixed a formula typo in decompose.md

---

docs/lang/new.md

fix #2560，将代码中的 `vector<T> V` 改为 `const vector<T>& V`，`auto vv` 改为 `const auto& vv`。
1. 注意有没有 typo

修改“可变参数模板的应用”中的代码

---

docs/basic/quick-sort.md

std::sort 使用的是内省排序，而非直接快排，在 `basic/stl-sort/` 中有详细说明
1. 注意有没有 typo

fix quick-sort

---

docs/tools/judgers.md

LemonLime upstream link change

---

docs/tools/judgers.md

update: leedagee/arbiter-distro project status

---

docs/contest/oi.md

HTTPS 无法进入页面，HTTP 可以。
1. 注意有没有 typo

修改 USACO 主页地址

---

docs/dp/tree.md

feat(dp/tree): add tree knapsack

---

docs/math/mobius.md

Update mobius.md 更改了例题二中不必要的分类讨论，并增加了线筛的推导过程

---

docs/graph/tree-divide.md

update the code for luogu 3806 to pass the test 7
1. 注意有没有 typo

Update code for luogu 3806 in tree-divide.md

---

docs/contest/resources.md

修复 「UOJ」和「vfk 的 OJ」分为两条的bug

---

docs/graph/virtual-tree.md

Update virtual-tree：优化表述 & 增加 cmp 代码

---

docs/math/mobius.md

修复了原文中 问题形势-「luogu 3768」简单的数学题-解法二 中存在的致命错误。
原作者可能由于手误推导错误，又没有经过检查，便认为是一种新解法发表了出来。
实质上正确推导解法二得到的最终形式，与解法一的最终形式本质完全相同。
同时修复了一些符号格式问题。
1. 注意有没有 typo

修复 问题形势-「luogu 3768」简单的数学题-解法二 中存在的致命错误.md

---

docs/graph/topo.md

1. 修正代码中的错误。
2. 改用 vector 存图。
3. 节点编号的范围改为 [0, n)，与上文的 Kahn 算法代码保持一致。
原代码第 8~9 行为：
```cpp
else if (!c[v])
dfs(v);
```
这么写的话，若对 `0->1, 1->2, 2->0` 这样的有环图做拓扑排序，仍然会返回 true。因此应改为下面这样：
```cpp
else if (!c[v])
if (!dfs(v))
return false;
```
1. 注意有没有 typo

修改 DFS 版拓扑排序的代码

---

docs/ds/dsu-complexity.md
mkdocs.yml

fix: 重构了并查集时间复杂度页面中的公式

---

docs/graph/mst.md

refactor(mst): 调换证明与实现的位置

---

docs/lang/new.md

Fix a typo

---

docs/basic/prefix-sum.md

1. fix typo https://github.com/OI-wiki/gitment/issues/269#issuecomment-694154374
2. 洛谷的 atcoder 提交 api 好像坏了，我就换成 vjudge 了，然后把洛谷的翻译搬运过去了。
3. fix formula https://github.com/OI-wiki/gitment/issues/269#issuecomment-694157479
1. 注意有没有 typo

fix typo && 修改题目网址 && fix formula

---

docs/graph/tree-centroid.md

---
【更改了代码实现】
更改了“/图论/树上问题/树的重心”内求树的重心的代码，使得它可以方便的求出树的两个重心。
变量的命名参考了原代码的命名方式，但有稍做修改。代码码风以 Google 的代码规范为参考。
【添加了一道例题】
为“/图论/树上问题/树的重心”添加了一道来自 CodeForces 的题目作为习题。
题目难度不难（评分 *1700），可以用于练习求解树的重心和求解树上问题。
---
1. 注意有没有 typo
---

更改了求树的重心的代码实现，并为该条目添加了一道例题。

---

docs/math/euler.md

改了一大堆。。。修复了不少之前的锅
1. 注意有没有 typo

优化euler.md逻辑、修复typo

---

docs/basic/quick-sort.md
docs/basic/stl-sort.md

modified:   docs/basic/quick-sort.md
modified:   docs/basic/stl-sort.md
由于内省排序在 quick-sort 中也有介绍，与 stl-sort 中原有的部分重复，因此对其进行了一些删改。

refactor[stl-sort.md, quick-sort.md]: 排序相关 STL

---

docs/graph/euler.md

fix[euler.md]: fix the wrong code block

---

docs/math/mobius.md

fix(mobius): 删除多余的 & 符号

---

docs/intro/htc.md

fix htc 套娃

---

.github/workflows/Gitee.yml

不在 fork 跑 GitHub Actions。现在在 fork push 一下 master 就会 fail。

ci(gitee): don't run in forks

---

docs/geometry/distance.md

修订 distance.md 中的一处细节

---

docs/basic/quick-sort.md

fix(quick-sort): remove confusing comments

---

docs/basic/quick-sort.md
docs/dp/knapsack.md

Fixed issue #2710.
1. 注意有没有 typo

Fixed issue #2710. Rearranged quick sort section and added more stuff.

---

docs/lang/pas-cpp.md

doc: fix misspell in pas-cpp

---

docs/graph/shortest-path.md

补充shortest-path内容

---

docs/dp/tree.md

fix: change ] to 」

---

docs/tools/editor/devcpp.md

fix #2713
因为 #2714 的 PR repository 已经被删除，故重新提交一次。
1. 注意有没有 typo

add(editor): Dev C++ download link

---

docs/string/kmp.md

- 对于真前（后）缀的举例
- 对于 \pi 函数的计算，取后缀的函数调用
1. 注意有没有 typo

修了一点 kmp 的小问题

---

docs/math/bignum.md

修复高精度计算页面一处 typo

---

docs/math/bignum.md

thanks @Harry-Chen
1. 注意有没有 typo

fix: 删除误导性的注释

---

docs/misc/parallel-binsearch.md

这个 PR 给整体二分加入了一个偏向竞赛风格的代码。原来的代码很好懂但不是很实用。
这个文章将来可能还要修一修。
---
1. 注意有没有 typo

feat: add CP-style code

---

docs/lang/csl/algorithm.md

Added next_permutation and examples for STL algorithm usage.

---

docs/dp/plug.md
docs/math/sieve.md

this link is invalid and is breaking oi-wiki-ng build
1. 注意有没有 typo

fix: remove niconico link

---

docs/graph/topo.md

add: practice problems in toposort

---

docs/dp/opt/slope.md

修正了 动态规划/DP 优化/斜率优化 中的一个错误。（这个错误害人不浅）
为图片添加了 "alt"
1. 注意有没有 typo

修正了 斜率优化 中的一个错误。

---

docs/math/gcd.md

fix: linebreak

---

docs/tools/editor/vim.md

原先提供的方法较为hacky而且容易改错，增加更好的方法。
我一个同学刚被这个坑了导致整个桌面环境都无法启动，所以提供一些更好的做法

修改 vim 介绍中关于交换 Caps Lock 和 ESC 的部分

---

docs/ds/dividing.md

顺便，什么时候把上面的 Pascal 代码换掉啊（
1. 注意有没有 typo

add 划分树解决动态逆序对问题

---

docs/ds/tree-decompose.md

- **BZOJ4812 由乃打扑克** 链接 由https://www.lydsy.com/JudgeOnline/problem.php?id=4812 替换为https://www.luogu.com.cn/problem/P5356.
- 因为原题出在luogu所以还是用luogu的链接了，不可以的化再替换: =)
1. 注意有没有 typo

Fix broken OJ link in ds/tree-decompose

---

docs/math/matrix.md

https://github.com/OI-wiki/gitment/issues/128#issuecomment-738738938

fix(matrix): fix typo

---

docs/math/prime.md

feat(prime): add a proof, closes #2814

---

docs/basic/binary-lifting.md

原来的链接坏掉了，导向的是 404 page
---
1. 注意有没有 typo

docs: (binary-lrfting) 修复坏链接

---

docs/ds/dsu.md

原代码:
```c++
void unionSet(int x, int y) {
// x 与 y 所在家族合并
x = find(x);
y = find(y);
if (x == y)  // 原本就在一个家族里就不管了
return;
fa[x] = y;  // 把 x 的祖先变成 y 的祖先的儿子
}
```
`if (x == y)` 那两行去掉后应该等价, 但是减少了一次跳转导致的分支预测开销.
**Update**: 分别运行 8 次, 平均运行时间为:
去掉 if     0.3431787 ms
不去掉 if 0.347336 ms
使用 [评测鸭](duck.ac) 评测, 数据为随机生成的 1e5 个元素随机合并 5000 次.
测试代码:
```cpp
#include <stdio.h>
#define MAXN 100000000
int fa[MAXN];  // 记录某个人的爸爸是谁，特别规定，祖先的爸爸是他自己
void makeSet(int size) {
for (int i = 0; i < size; i++) fa[i] = i;  // i就在它本身的集合里
return;
}
int find(int x) {
if (x != fa[x])  // x不是自身的父亲，即x不是该集合的代表
fa[x] = find(fa[x]);  // 查找x的祖先直到找到代表,于是顺手路径压缩
return fa[x];
}
void unionSet(int x, int y) {
// x 与 y 所在家族合并
x = find(x);
y = find(y);
if (x == y)  // 原本就在一个家族里就不管了
return;
fa[x] = y;  // 把 x 的祖先变成 y 的祖先的儿子
}
int …
```

提升并查集示例代码性能

---

docs/geometry/nearest-points.md

Due to Code Jam update, this link was inaccessible before.
1. 注意有没有 typo

fix(nearest-points): unhide a link

---

docs/math/simplex.md

fix a typo in simplex.md

---

docs/graph/flow/max-flow.md

docs: (max-flow) 增加 EK 算法的注释

---

docs/graph/mst.md

Fix(mst): maintain author list

---

docs/misc/random.md

feat(random): add pseudo random number generator

---

docs/graph/concept.md

Update(graph/concept): fix the defination of closed subgraph

---

docs/string/trie.md

将 01-trie 合并 表述中的 "marge" 更正为 "merge" 以符合语义。

将 01-trie 合并 表述中的 "marge" 更正为 "merge"

---

docs/math/poly/ntt.md

单位根g_n应为g^q\pmod p，原公式g_n=g^p\pmod q有误

fix(ntt.md):修复了公式

---

docs/dp/opt/monotonous-queue-stack.md

修改朴素多重背包时间复杂度

---

docs/lang/csl/container-adapter.md

refactor: unify coding style & improve text

---

docs/tools/editor/devcpp.md

feat(devcpp.md): add Embarcadero Dev-C++

---

docs/misc/stern-brocot.md

https://github.com/OI-wiki/gitment/issues/341#issuecomment-765967175
1. 注意有没有 typo

fix(stern-brocot): fix typo

---

.github/workflows/Gitee.yml

ref: https://github.com/Yikun/hub-mirror-action#%E7%BB%84%E7%BB%87%E5%90%8C%E6%AD%A5

ci: sync all repos

---

docs/tools/editor/guide.md

\[1]: https://github.com/OI-wiki/OI-wiki/issues/2664#issuecomment-767561469
[2]: https://github.com/OI-wiki/OI-wiki/pull/2913#discussion_r564797860
left TODO:
- way to install on Fedora (depend on a `checkinstall` package on OBS/Copr for Fedora)

feat(tool/editor/guide.md): add way to install GUIDE

---

README.md
docs/index.md

https://ctf-wiki.github.io/ctf-wiki to https://ctf-wiki.org

fix(index.md): using CTF Wiki new link

---

docs/basic/construction.md

fix(construction): add author

---

docs/tools/wsl.md

[1]: https://www.debian.org/doc/manuals/debian-reference/ch02.zh-cn.html

refactor(tool/wsl.md): using Debian Package Management Manual

---

docs/lang/python.md

```
fix(lang/python.md): python interpreter name and symlink
fix(lang/python.md): using `console` instead of `bash`
```

fix(lang/python.md): python interpreter name and symlink

---

docs/intro/faq.md

Python Script by lilydjwg: https://gist.github.com/lilydjwg/93d33ed04547e1b9f7a86b64ef2ed058
Introduction by lilydjwg: https://blog.lilydjwg.me/2019/8/16/gh-check.214730.html
Perl Script by hellojukay: https://gist.github.com/lilydjwg/93d33ed04547e1b9f7a86b64ef2ed058#gistcomment-3401138

feat(intro/faq.md): add gh-check script to get fastest GitHub IP

---

docs/graph/tree-diameter.md

fix(tree-diameter.md): 修改了示例代码与例题的格式

---

.github/workflows/Gitee.yml

Revert "ci: sync all repos"

---

README.md

chore: change travis badge

---

docs/dp/dynamic.md

feat(dynamic.md): 添加了一些习题

---

docs/tools/editor/emacs.md

Add description for Language Server, Org Mode and ELPA.

---

docs/graph/mdst.md

添加了一个mdst 最小直径生成树的实现
1. 注意有没有 typo

Update mdst.md 添加mdst的参考实现

---

docs/math/poly/lagrange.md

fix(lagrange.md): error fix

---

docs/ds/wblt.md

删除 wblt.md 的无意义注释

---

docs/ds/seg-beats.md

Update seg-beats.md 添加一道题的参考实现

---

docs/misc/stern-brocot.md

update(stern-brocot): wrap multiline math code in aligned env

---

docs/intro/faq.md

update to the latest hosts

---

docs/math/quick-pow.md

The one at the top is enclosed by `mathrm`, which looks a bit nicer, IMO.

Adding mathrm for non-math elements in the math mode

---

.remarkignore

This pr makes bot ignore problematic files

feat: add ignore file

---

.github/workflows/build-pdf.yml

ci: add inkscape

---

docs/contest/oi.md
docs/dp/basic.md
docs/dp/opt/monotonous-queue-stack.md
docs/dp/opt/quadrangle.md
docs/dp/opt/slope.md
docs/dp/opt/state.md
docs/ds/seg.md
docs/ds/tree-decompose.md
docs/geometry/distance.md
docs/graph/bfs.md
docs/graph/cut.md
docs/graph/dfs.md
docs/graph/hld.md
docs/graph/tree-centroid.md
docs/math/du.md
docs/math/min-25.md
docs/math/poly/lagrange.md
docs/search/opt.md
docs/string/kmp.md
docs/string/z-func.md

chore: update contributor list

---

docs/lang/csl/algorithm.md

修复了错误的merge用法 新增inplace_merge
1. 注意有没有 typo

Update algorithm.md 修正merge使用错误 新增inplace_merge

---

docs/lang/pb-ds/tree.md

添加__gnu_pbds::tree
1. 注意有没有 typo

Update tree.md 添加__gnu_pbds::tree

---

docs/basic/construction.md

chore: translate problem desc

---

docs/ds/hash.md

Update hash.md 添加闭散列法的一个实现

---

docs/tools/oj-tool.md

fix(oj-tool): update CP Editor

---

docs/graph/shortest-path.md

remove 的原因见 https://github.com/OI-wiki/gitment/issues/45#issuecomment-727084862 。
移除了算法描述和代码实现，改为在 Bellman-Ford 算法的优化下提及了大概思路。
1. 注意有没有 typo

fix(shortest-path): remove D´Esopo-Pape algo

---

docs/string/sa.md

见 https://github.com/OI-wiki/gitment/issues/110#issuecomment-780279376

修正比较子串大小关系内容

---

docs/search/dlx.md

[BUG]DLXinsert功能代码出错

---

docs/lang/java.md

Use '' to wrap a char

---

docs/lang/java.md

fix: typos in Java.md

---

README.md

https://t.me/c/1344172945/99727

fix: render math example link

---

docs/contest/resources.md

Add a great training sheet for newbies.

Add a great training sheet to resources.md

---

docs/contest/resources.md
docs/math/quick-pow.md

完善了 $O(1)$ 快速乘相关内容

---

docs/math/inclusion-exclusion-principle.md

补充了 min-max 容斥相关内容

---

docs/math/lucas.md

格式修改，修复 typo

---

docs/math/mobius.md

补充了 Dirichlet 卷积相关内容

---

docs/string/sa.md

差别见提交 <https://loj.ac/s/1088930> 与 <https://loj.ac/s/1088931> 在 <https://judge.yosupo.jp/submission/41752> 也可通过。
但是可能仍有冗余操作，因为我看到有人的写法是当排名不同时直接返回而不用再生成后缀数组，但我也不太懂，审核大大再看看吧。
1. 注意有没有 typo

给后缀数组加了一个基础的优化

---

docs/math/mobius.md

修了一下莫比乌斯反演那页的一个挂掉的公式

---

docs/math/lucas.md

typo fix : 部分 q 写成 p

---

docs/math/meissel-lehmer.md
mkdocs.yml

Feat meissel-lehmer

---

docs/basic/prefix-sum.md
docs/math/meissel-lehmer.md

更新树差分中的文字错误

---

.github/workflows/build-pdf.yml
docs/math/meissel-lehmer.md

ci(pdf): fix pdf build

---

docs/dp/state.md

AHOI 2009 的这道 中国象棋 应该并不是典型的状压 dp 题，甚至没有状压解法。
添加了个人认为比较入门的几道状压 dp 题
1. 注意有没有 typo

fix state.md：习题推荐有误

---

.github/workflows/build-pdf.yml

with https://github.com/OI-wiki/OI-Wiki-export/pull/9

fix: add `-8bit` for minted represents tabs as ^^I

---

.github/workflows/build-pdf.yml

fix(ci): pdf postion

---

docs/math/drawer-principle.md

- 修正了排版
- 强化floor为ceil
- 添加集合语言的叙述
- 添加了包含例题的参考文献

重写了鸽巢原理的介绍

---

docs/math/integral.md

1. 注意有没有 typo
在调用这个板子时，很多时候如果没有这个最少迭代步数，会导致WA。因此打一个小补丁。

增加了自适应Simpson积分的迭代次数细节（小补丁）

---

docs/graph/lca.md

修复了LCA转RMQ内容描述错误

---

docs/graph/dsu-on-tree.md

closes #2421
1. 注意有没有 typo
在阅读 [参考文献](https://codeforces.com/blog/entry/44351) 后我认为原来的代码是错误的。
由于我写的代码与算法的描述有出入，所以也对算法描述有修改
代码有经过验证。如果需要，可以用 [暴力](https://paste.ubuntu.com/p/9vBpF2QN6K/) 和 [数据生成器](https://paste.ubuntu.com/p/rsSJcz74Nj/) 来对拍

Fix(graph/dsu-on-tree): rewrite code implementation of example problem

---

docs/math/poly/fft.md

1. 注意有没有 typo
之前有看到别人写的“另类”的 FFT 代码，所以研究了一下

feature(math/poly/fft.md): add another method for IDFT

---

.github/workflows/build-pdf.yml

see https://github.com/OI-wiki/OI-Wiki-export/pull/11

fix: update pdf build script

---

docs/math/mobius.md

fix: 修复莫比乌斯反演的一个公式

---

docs/_static/js/extra.js

fix (#3099): incorrect time display format

---

docs/math/bignum.md

修复示例代码中的错误

---

docs/string/hash.md

feature(string/hash.md): update code of example problem

---

docs/lang/csl/container-adapter.md

增加第四种pq构造方式

---

docs/ds/seg.md

fix mistakes in #3144

---

docs/lang/csl/pair.md

fix pair typo

---

docs/tools/editor/devcpp.md

在devcpp.md加入了小熊猫Dev-C++的描述

---

docs/ds/treap.md

fix the wrong operation on size[k] when deleting an element that not exist on the treap
1. 注意有没有 typo

bugfix: treap delete an invalid element

---

docs/ds/seg.md

feat(ds/seg): add historic references

---

docs/_redirects

fix: fix redirect for var

---

docs/math/sieve.md

更改了欧拉筛对应的代码：原代码是埃筛，与文字描述不符
1. 注意有没有 typo

Update sieve.md 修改欧拉筛代码

---

README.md

fix: license

---

docs/lang/array.md

```plain
Co-authored by: XuLongjia<38058181+XuLongjia@users.noreply.github.com>
As in https://github.com/OI-wiki/gitment/issues/367#issuecomment-852131420
```
1. 注意有没有 typo

fix(lang/array): wrong code

---

mkdocs.yml

disable: strict mode

---

docs/dp/images/domino_v2_transform_matrix.svg

On Thursday, June 10, 2021 8:56 AM, ksyx wrote:
> 但是在最后一张 matrix 上希望能够带上原来线条的颜色，目前的 svglize 可能会使读者有一定的阅读困难
**审核的同学** 请着重关注以下方面：
- 请**尽量**保持跟进直到它被 merge 或 close

fix(domino_v2_transform_matrix.svg): line colors

---

docs/graph/tree-centroid.md

为树的重心页面添加几个链接

---

docs/graph/flow/max-flow.md

format(graph/flow/max-flow): 调整脚注

---

docs/math/quad-residue.md

Fix a typo in quad-residue.md

---

docs/math/primitive-root.md

修复原根存在性证明中的笔误

---

docs/math/prime.md

bugfix: change the invalid url to the valid one

---

docs/tools/latex.md

更新参考文档LATEX 2ε的链接 另外https://github.com/OI-wiki/libs/blob/master/latex/lshort-zh-cn.pdf可以删了

fix:update latex.md(Link to LATEX 2ε)

---

docs/misc/cc-basic.md

feat(cc-basic): add an explanation why co-NP?=NP is not obivious

---

docs/math/notation.md

fix(math/notation): fix link to 渐进符号

---

docs/misc/expression.md

修正”表达式求值“代码的大括号匹配

---

.github/workflows/build-pdf.yml

fix pdf build

---

docs/basic/complexity.md

feat(basic/complexity): add Python example

---

docs/string/z-func.md

Z 函数线性算法的最后一步应该是当 $i+z[i]-1>r$ 时进行更新

修复了 Z 函数 页面的一个错误

---

docs/contest/common-mistakes.md

chore(common-mistakes): fix indention

---

docs/contest/resources.md

LibreOJ 现基于 [SYZOJ NG](https://github.com/syzoj/syzoj-ng)。
1. 注意有没有 typo

SYZOJ -> SYZOJ NG

---

docs/tools/editor/sublime3.md

Fix typo in sublime3.md

---

docs/math/quick-pow.md

corner case: binpow(123, 0, 1)
where the anwser should be 0 instead of 1
1. 注意有没有 typo

fix(math/quick-pow): initialize res to 1%mod in case exp=0 and mod=1

---

docs/graph/flow.md

添加网络流 24 题的洛谷题目链接

---

docs/math/prime.md

按<https://en.wikipedia.org/wiki/Miller%E2%80%93Rabin_primality_test>修改了部分代码，问题主要是多了一步循环。
1. 注意有没有 typo

修改了Miller-Rabin的代码问题

---

docs/string/manacher.md

fix:code error is docs/string/manacher

---

.github/ISSUE_TEMPLATE/content-request.yml

fix: content request form

---

docs/graph/scc.md

补充了Kosaraju算法的作者
1. 注意有没有 typo

feat(graph/scc.md) : 补充了Kosaraju算法的作者

---

docs/tools/cmd.md

https://www.gnu.org/software/make/manual/html_node/Catalogue-of-Rules.html

feat(tool/cmd): add GNU Make built-in rule

---

docs/math/powerful-number.md

fix: 修改了1处笔误

---

docs/math/prime.md

fix(math/prime): fix a typo

---

mkdocs.yml

the author of #3168 forgot to update TOC while adding a new page.

fix(mkdocs.yml): update TOC

---

docs/math/mobius.md

fix(math/mobius): typo

---

docs/string/kmp.md

文中关于字符串周期部分，关于所有border长度的部分，个人认为有点小问题，第二长的border应为$\pi[\pi[n-1]-1]$，而原文中写的是$\pi[\pi[n-1]]$

fix(kmp): 关于文中字符串周期部分的小问题

---

docs/misc/hoverline.md

原本代码有较多错误，修改后可以 AC
1. 注意有没有 typo

fix(misc/hoverline):  fix code error

---

docs/math/poly/fft.md

大写的 F 函数下面都没有用到，看起来稍有点迷惑，延续使用小写 f 函数貌似更好。
1. 注意有没有 typo

fix(math/poly/fft): fix function name lowercase

---

docs/basic/heap-sort.md

1. 在英语表述中，父结点和子结点用的是 Parent 和 Child 而非 dad and son
2. 发现了「节点」和「结点」混用的情况，统一措辞为「节点」
ref: https://www.termonline.cn/word/168033/1#s1
1. 注意有没有 typo

fix(basic/heap-sort.md): 修改部分用词

---

docs/intro/format.md

close https://github.com/OI-wiki/OI-wiki/issues/3422

feat(format-manual): prefer APNG rather than GIF

---

docs/math/char-poly.md
docs/math/poly/czt.md

修复了一下显示问题，看起来对于 `[]()` 这样的数学符号会识别成 MarkDown 的东西而导致显示问题？
另外修了一下丢了的一个加号。。
1. 注意有没有 typo

Fix czt.md

---

docs/tools/editor/devcpp.md

简单的说，感觉所谓「介绍」就只是项目历史简介，显得冗余杂乱。因此对该部分进行了重写。
目前该pr缺少对devcpp的缺点描述（可能不必须
1. 注意有没有 typo

fix: 重写devcpp的介绍部分

---

docs/math/gauss.md

feat(gauss.md): 增加了关于使用高斯消元法解异或方程组的方法与一道题目

---

docs/basic/enumerate.md

需要找的是记录下来的相反数

---

docs/math/quick-pow.md

fix #3381 
在“快速幂”一节中加入了光速幂的相关内容。（`commit message` 中的“一道例题”实际上并没有添加，是当时 `commit` 的时候忘记删掉了的ww）
1. 注意有没有 typo

feat: 增加了光速幂（块速幂）的思路与实现; fix #3381

---

docs/lang/csl/index.md
docs/math/poly/czt.md

NOI Linux 2.0 对 g++ 环境的更新
1. 注意有没有 typo

feat: NOI Linux 2.0 对 g++ 环境的更新

---

docs/ds/seg.md

修改笔误。
https://github.com/OI-wiki/gitment/issues/173#issuecomment-895942632  
https://github.com/OI-wiki/gitment/issues/173#issuecomment-899425755
1. 注意有没有 typo

Fix(ds/seg): 修改求 mid 时的笔误

---

docs/math/poly/ntt.md

Change a deprecated link to "primitive root"

Update a deprecated link in ntt.md

---

docs/dp/plug.md

Add a letter to fix the math formula error.
1. 注意有没有 typo

fix(dp/plug.md): Fix a formula error

---

docs/math/schreier-sims.md
mkdocs.yml

- docs/math/schreier-sims.md
- mkdocs.yaml
close #1596
1. 注意有没有 typo

add(math/schreier-sims): Add Schreier–Sims Algorithm

---

docs/math/game-theory.md

Change operatorname{} to \operatorname{}
1. 注意有没有 typo

fix: bad LaTeX format

---

docs/intro/htc.md

完成 https://github.com/OI-wiki/OI-wiki/issues/3478 中所提及的内容。

refactor(intro/htc): Add GitHub Web-Based Editor

---

docs/math/number-theory/basic.md

原来的 latex 不能正常显示，现加以修改，并扩充了原有的内容。
1. 注意有没有 typo

修改并扩充了数论-数论基础中的同余的性质

---

docs/math/combinatorics/eulerian.md

Fix LaTeX error of Eulerian Number.

---

docs/contest/interaction.md
docs/ds/dsu.md
docs/ds/finger-tree.md
docs/geometry/inverse.md
docs/geometry/nearest-points.md
docs/geometry/triangulation.md
docs/math/fourier-motzkin-elimination.md
docs/math/group-theory.md
docs/math/number-theory/meissel-lehmer.md
docs/math/order-theory.md
docs/math/poly/intro.md
docs/math/schreier-sims.md
docs/math/young-tableau.md
docs/misc/15-puzzle.md
docs/misc/garsia-wachs.md

fix: replace "Reference"

---

docs/tools/editor/sublime3.md

修复 sublime3.md 一个全角双引号为半角

---

.github/workflows/celebration.yml
scripts/celebration.py

ci: automatically create star celebrations

---

docs/lang/basic.md

于247行，样例使用的是 `#ifdef` 而非 `#if`，故改之。
1. 注意有没有 typo

fix: minor fix in docs/lang/basic.md

---

docs/geometry/images/scanning.svg

fix(geometry/scanning): missing segtree cnt

---

docs/math/number-theory/basic.md

fix(number-theory/basic): Fix a formula error.

---

docs/tools/cmd.md

fix(tool/cmd): some software only support `-h`

---

docs/math/poly/fwt.md

feat: 为FWT页面添加了一道今年的非模板例题

---

Dockerfile
docs/intro/docker-deploy.md

fix #3104 
- 更换新的Ubuntu版本以支持pip
- 更换加速git链接以提高clone成功率
- 注释掉不再推荐（且我本地会出BUG）的Maintainer标注，虽然我不知道应该改成设么样（因为没研究过Docker实际上）。

fix: Dockerfile #3104

---

docs/ds/code/seg/seg_1.cpp

这个地方并不是“懒标记相加”。
位运算改成*2更符合上文的代码，也更易懂。

修正一个线段树模板注释的小错误

---

docs/math/poly/fft.md

对于``为什么用 $n+1$ 个点就能唯一地表示这个函数''，加了一个（可能更好的）证明。
1. 注意有没有 typo

feat(math/poly/fft): better proof

---

docs/lang/class.md

fix(lang/class.md): Missing variable declaration

---

docs/math/number-theory/prime.md
docs/math/number-theory/sieve.md

fix(number-theory/prime, sieve): fix format & logical error

---

docs/intro/docker-deploy.md

https://github.com/OI-wiki/OI-wiki/pull/3670#issuecomment-974781322

fix: fixed Ubuntu version of docker deploy

---

docs/string/pam.md

According to https://github.com/OI-wiki/gitment/issues/109#issuecomment-925649786
还有，PAM 不是回文自动机吗（
1. 注意有没有 typo

Fix(string/pam): 修正例题题意

---

docs/intro/docker-deploy.md
docs/math/number-theory/primitive-root.md

修正了原根部分的一个小错误

---

docs/intro/htc.md

fix(intro/htc): replace "Travis CI" with "GitHub Actions"

---

docs/graph/min-circle.md

In the Floyd algorithm python implement, the code indentation is wrong.

fix(docs/graph/min-circle): indentation error on python code

---

docs/intro/format.md

Changed the old link of the document which doesn't exist now into the new one.

fix(intro/format): fix broken link

---

.github/workflows/pr-stale.yml

feat: add Pull Request auto stale

---

docs/intro/mirrors.md
mkdocs.yml

目前只加上了我目前知道的镜像站，可能还有一些镜像站我没有加上的，麻烦补充。
这个PR是一个不太成熟的想法，欢迎提出各种意见

feat: 添加了镜像站列表

---

.github/workflows/pr-stale.yml

fix: change crontab expression to run weekly

---

docs/tools/judger/index.md
mkdocs.yml

fix: tools/judger/index 不在目录中 (#3709)

---

docs/string/kmp.md
docs/string/lyndon.md

fix(string/kmp, string/lyndon): fix error in python code of substr

---

docs/ds/persistent-seg.md

fix(ds/persistent-seg): 修改代码注释使描述更清晰

---

docs/tools/special-judge.md

fix(tools/special-judge): LibreOJ is no longer using SYZOJ 2

---

.github/workflows/build.yml

ci: add `workflow_dispatch` to manually trigger github workflow

---

mkdocs.yml

2022 Happy New Year!

---

docs/lang/csl/iterator.md

修正了现行NOI规则对auto关键字的限制（现行NOI规则规定的C++14已完全支持auto关键字）

Updated: Keyword auto is now supported by NOI.

---

docs/lang/python.md

fix(python): typo

---

docs/math/number-theory/lucas.md

fix(math/lucas): formula appearance

---

docs/contest/resources.md

更新了关于 LibreOJ 的相关信息
1. 注意有没有 typo

fix(contest/resources): Update Introduction of LibreOJ

---

docs/contest/resources.md

fix(resources.md): book author typo

---

docs/ds/code/seg-beats/seg-beats_3.cpp

fix(ds/seg-beats): CPU监控示例代码

---

.github/workflows/pr-stale.yml

添加了 等待审核 等待合并 等待取消修改请求 三个label进忽略列表

feat(ci/pr-stale): add ignore labels

---

docs/ds/code/block-list/block-list_1.cpp

via <https://github.com/OI-wiki/gitment/issues/170#issuecomment-818477389>
1. 注意有没有 typo

fix(ds/block-list): Remove useless variable

---

docs/lang/csl/algorithm.md

fix(csl/algorithm): 修复对 `std::shuffle` 所接受的随机数生成器的解释

---

docs/lang/csl/algorithm.md

fix(csl/algorithm): 修正 #3754 引入的代码中的中文分号

---

docs/lang/branch.md

feat(branch.md): switch cases can be unordered

---

docs/contest/resources.md

feat(contest/resources): 添加课程

---

docs/tools/wsl.md

1. 增加了推荐的 wsl 安装方法
2. 增加了关于 WSLg 的提示
3. 删除关于 WSL 1 与 WSL 2 的比较部分
4. 简单调整了结构和部分语言表达
5. 删除一条孤立的脚注
*测试: 此 commit 使用 [editor.akioi.icu](editor.akioi.icu) 创建*
1. 注意有没有 typo

feat(wsl): various fix and add modern install method

---

docs/lang/pb-ds/tree.md

fix(lang/pb-ds/tree.md): 提升排版

---

docs/string/sa.md

fix(string/sa): missing checking code

---

docs/contest/resources.md

feat(resources): USACO Guide

---

docs/contest/resources.md

feat(contest/resources): 添加内容

---

mkdocs.yml

chore(toc): move problemsetting to upper level

---

docs/ds/sqrt-tree.md

feat(sqrt-tree): 完善链接标题

---

docs/ds/dsu.md

fix:(dsu.md): 添加了非递归版本的代码

---

docs/lang/python.md

- 淘宝 NPM 镜像换了域名，我这时发现他们取消了 Python 镜像。
- @ZenithalHourlyRate 上线了个站，可以供读者查到更多关于 PyPI 的镜像： https://mirrorz.org/list/pypi
1. 注意有没有 typo

chore(docs): 关于 Python 镜像链接的变化

---

docs/intro/faq.md

1. 注意有没有 typo
This is an emergency FastGit UK product update. Please merge asap.
Best,
KevinZonda
Director of FastGit UK

update(intro/faq): fastgit link

---

docs/misc/parallel-binsearch.md

fix(parallel-binsearch.md): 修正最后一段代码中变量名错误

---

docs/lang/python.md

feat(lang/python.md): introduction of decorator

---

mkdocs.yml

fix(mkdocs.yml): 完善格式

---

docs/lang/python.md
docs/math/poly/fft.md

fix(math/poly/fft): Fix Collapsible Block

---

scripts/test.py

- 在代码文件文件夹下建立文件名.skip_test可以跳过测试此文件
- 测试功能写的太乱了

feat(test): add skip_test

---

docs/math/number-theory/sqrt-decomposition.md

n / (n / l) 应为 n / l 。
1. 注意有没有 typo

fix(number-theory/sqrt-decomposition.md): 修改数论分块中伪代码的一处错误

---

docs/geometry/triangulation.md

[Codeforces Gym 103485M. Constellation collection](https://codeforces.com/gym/103485/problem/M) 三角剖分之后建图进行 Floodfill
1. 注意有没有 typo

feat(geometry/triangulation.md) 添加一道例题

---

docs/math/berlekamp-massey.md
mkdocs.yml

feat(math/berlekamp-massey.md): 添加 Berlekamp-Massey 算法页面

---

docs/math/number-theory/sieve.md

fix(sieve.md): 修正了筛法求约数和中的一个错误
1. 注意有没有 typo

fix(sieve.md): 修正了筛法求约数和中的一个错误

---

docs/basic/merge-sort.md

It's a wrong statement without these two brackets
1. 注意有没有 typo

fix(/docs/basicmerge-sort.md): fix an omitting of brackets

---

docs/search/dfs.md

python版本的dfs，把读入的n,m转化为int类型再传入dfs()
1. 注意有没有 typo

fix(dfs.md): python版本的dfs，把读入的n,m转化为int类型再传入dfs()。原版本是str类型，会报错。
