OI-wiki/OI-wiki

docs/ds/lct.md
docs/ds/splay.md
docs/graph/hld.md
docs/math/dictionary.md

fix: 将失效的 BZOJ 链接指向 HydroOJ/BZOJ

---

docs/graph/shortest-path.md

fix(shortest-path): fix cpp code of bellman-ford algorithm

---

docs/misc/mo-algo-on-tree.md

修正了一个下标错误，把除号改为了分数形式
1. 注意有没有 typo

fix(misc/mo-algo-on-tree): fix latex

---

docs/contest/resources.md

补充一个开源的在线评测系统 [WZOI](https://wzoi.cc)

feat(/docs/contest/resources): 补充国内在线评测平台

---

docs/contest/resources.md

feat(contest/resources): Add more tools

---

docs/basic/merge-sort.md

md43行，伪代码13行 p=rr 疑似为p=ll，后面的c++和python都是给p赋值ll
1. 注意有没有 typo

fix(basic/merge-sort): 修改伪代码的变量错误

---

requirements.txt

https://t.me/c/1344172945/129942

chore(python): lock dependency versions

---

docs/math/number-theory/gcd.md

fix typo in the proof of gcd
1. 注意有没有 typo

fix(math/number-theory/gcd.md): fix typo

---

docs/string/match.md

``` go
i := 0
for i = 0; i < n; i++ 
```
when loop completes (without any break), `i == n`. 
```python
for  i  in  range ( 0 , n )
```
when the loop completes, the value of `i` will be `n-1`. the reason being, `i` is not updated instead it gets value from the `range` function, and the `range` function returns the value `v` such that `v < n`.

fix(string/match): Fix condition

---

docs/math/number-theory/crt.md

* Add pseudo code for Garner's Chinese remainder algorithm
1. 注意有没有 typo

feat(math/number-theory/crt.md): Add pseudo code

---

docs/math/number-theory/bsgs.md

feat(math/number-theory/bsgs)：增加了对要求 a,p 互质的解释

---

docs/math/number-theory/prime.md

feat(number-theory/prime): add an introduction about explicit bounds of test number for Miller-Rabin primality test

---

docs/ds/leftist-tree.md
docs/math/number-theory/wilson.md

fix(leftist-tree): Fix randomized heap's code

---

docs/graph/matrix-tree.md

fix(graph/matrix-tree): 修复了引理 1 的渲染

---

docs/dp/knapsack.md

fix(dp/knapsack.md): fix compile error

---

docs/math/number-theory/sieve.md

feat(sieve): 删除冗余语句

---

docs/math/number-theory/euler.md

fix(math/number-theory/euler.md): 修复latex中的中文括号

---

docs/graph/graph-matching/general-match.md

fix(graph/graph-matching/general-match.md): 补上了文中缺失的示例图片

---

docs/lang/java.md

为 Java 增加了一个改动自 [Kattio.java](https://github.com/Kattis/kattio/blob/master/Kattio.java) 的，更有效率的 IO 写法。
------
1. 注意有没有 typo

feat(lang/java): 为 Java 增加一个更有效率的 IO 写法

---

docs/lang/pb-ds/pq.md

feat(lang/pb-ds/pq): __gnu_pbds 迭代器的失效保证

---

docs/lang/pas-cpp.md

将VSCode从IDE分类中移至文本编辑器分类。
1. 注意有没有 typo

fix(docs/lang/pas-cpp.md): 修改VSCode分类到文本编辑器中

---

docs/ds/dsu.md

fix(ds/dsu.md)：参考文献链接失效，换了个新的

---

docs/dp/basic.md

fix(dp/basic.md): 修正 LCS 的描述和代码

---

docs/dp/knapsack.md

fix(dp/knapsack.md): fix a typo

---

docs/contest/resources.md

fix(resources): replace invalid link

---

docs/search/dlx.md

fix(search/dlx): remove indentation

---

docs/graph/lca.md

欧拉序列的`dfs`函数代码原为
```cpp
void dfs(int t, int depth) {
dfn[++dfntot] = t;
pos[t] = dfntot;
dep[dfntot] = depth;
for (int i = head[t]; i; i = side[i].next) {
dfs(side[i].to, t, depth + 1);//here is a bug
dfn[++dfntot] = t;
dep[dfntot] = depth;
}
}
```
但`dfs`只有两个参数，所以此`commit`删去了多余的那一个
1. 注意有没有 typo

fix(docs/graph/lca.md): 修改欧拉序列的代码

---

docs/contest/resources.md

Competitive Programmer's Handbook appears twice on the page.
Removed one of them.
1. 注意有没有 typo

fix(contest/resources.md): remove repetitive book.

---

docs/graph/scc.md

第 15 行“算法结构”->“算法和数据结构”。
1. 注意有没有 typo

fix(graph/scc.md): 改错别字

---

docs/graph/shortest-path.md

添加了Dijkstra算法的Python版本的优先队列实现（之前的页面只有这部分算法的C++实现）。
1. 注意有没有 typo

feat(docs/graph/shortest-path.md):添加Python版Dijkstra算法

---

docs/geometry/2d.md

原公式渲染后并不能正确的表达原本想要表达的含义，容易误解为 i%(n+1), 实际应为 (i%n)+1, 通过添加括号修正了错误
1. 注意有没有 typo

fix(docs/geometry/2d.md): 修正了求任意多边形面积一节中公式的错误

---

docs/math/number-theory/quad-residue.md

* 修正一处错误（我写的）
谢谢洛谷的 happydef 指出。
1. 注意有没有 typo

fix(math/number-theory/quad-residue.md): fix

---

docs/math/poly/ntt.md

fix(math/poly/ntt): 修复NTT笔误

---

docs/math/poly/ntt.md

fix(math/poly/ntt): 修复参考资料笔误

---

docs/ds/seg.md

将区间修改为特定值时，和区间修改增加不同，无法通过修改值是否为0来判断修改是否合法，因此需要引入额外的空间储存是否发生修改，即新增的 `v[p]` 代表索引为 p 的区间打上了修改标记
1. 注意有没有 typo

fix(ds/seg): 修正线段树区间赋值代码

---

docs/graph/mod-shortest-path.md

feat(graph/mod-shortest-path): 例题部分增加最近 AGC 中的题目

---

docs/geometry/scanning.md

fix(geometry/scanning): 修正错误链接及题号

---

docs/lang/file-op.md

fix(lang/file-op): 修改样例代码使其通过编译

---

docs/misc/modifiable-mo-algo.md

chore(misc/modifiable-mo-algo): 增加前往“普通莫队算法”页面的链接

---

docs/basic/selection-sort.md

fix(selection-sort.md):将 C++ 中的第 10 至第 12 行代码替换为 swap 函数。
1. 注意有没有 typo

fix(basic/selection-sort.md): 将 C++ 交换变量代码替换为 std::swap 函数

---

docs/math/number-theory/wilson.md

fix(number-theory/wilson): typo

---

CITATION.bib

添加此文件后可以为存储库的右侧信息栏中添加「Cite this repository」项。
---
1. 注意有没有 typo

chore: add citation file

---

docs/math/number-theory/gcd.md

feat(math/number-theory/gcd): 增加了一些代码示例

---

docs/ds/treap.md

fix(ds/treap): 修复 ”按值分裂“ 部分的一个写错的 latex

---

docs/misc/josephus.md

补充了递推上将求模变为分类讨论的依据,修改了之前失败PR内的一个错误

feat(josephus.md)对递推式补充解释(正确版)

---

.github/workflows/build.yml
netlify.toml
scripts/post-build/commits-info/render-commits-info.sh

ci: switch to node 16

---

scripts/post-build/math/task-handler.ts

https://t.me/c/1344172945/136642

fix(scripts/post-build/math): mathjax.css relative path calculating

---

docs/graph/code/mod-shortest-path/mod-shortest-path_1.cpp
docs/misc/code/hill-climbing/hill-climbing_1.cpp
docs/string/code/suffix-bst/suffix-bst_2.cpp

fix warnings that ci says (cpp)

fix: code warnings

---

docs/intro/htc.md

正如 #4017 所提到的，有一部分贡献者在对 Pull Request 的内容进行更新时没有正确的操作，导致更改被分布在多个下游分支中，该 Pull Request 增加了相关的解释，帮助贡献者进行正确的更改。
1. 注意有没有 typo

feat(intro/htc): 增加关于继续向 Pull Request 追加修改的步骤 (#4017)

---

docs/graph/code/tree-divide/tree-divide_1.cpp
docs/graph/code/tree-divide/tree-divide_2.cpp
docs/graph/code/tree-divide/tree-divide_3.cpp
docs/graph/lca.md

fix(graph/lca): typo in math formula

---

scripts/post-build/commits-info/task-handler.ts

每个文件的两次 `git log` 合并成了一次，并且添加了 `--follow` 选项（准确性提升（`--follow`）有待观察）。

refactor(scripts/post-build/commits-info): optimize performance and precision

---

.mergify.yml

This change has been made by @Enter-tainer from https://mergify.com config editor.

ci(Mergify): introduce Mergify

---

Pipfile
Pipfile.lock

之前的pipfile里面没有 request, 导致庆祝失败 https://github.com/OI-wiki/OI-wiki/runs/7390429738?check_suite_focus=true

ci: fix celebration by adding requests to Pipfile

---

docs/ds/seg.md

和上文的代码结构保持一致，而且换行后观感以及阅读体验都好很多
谢谢！

fix(ds/seg): 优化代码结构，使上下文一致，提高阅读体验

---

docs/basic/complexity.md

fix(basic/complexity): latex <= -> \leq

---

.github/workflows/build-pdf.yml

chore: rename LaTeX workflow

---

docs/ds/persistent-in-bit.md

fix(ds/persistent-in-bit): 修复指向 ZOJ 的链接

---

docs/ds/images/segt4.svg

fix(ds/segt4.svg): 解决 Windows 上 Microsoft Edge 显示图片异常的问题（部分数字不在框内）

---

docs/string/sam.md

fix(sam.md): “两个字符串的最长公共子串”的示例代码中，返回值应为`T.substr(bestpos - best + 1, best)`,而非`t.substr(bestpos - best + 1, best)`
1. 注意有没有 typo

fix(string/sam): 修正 “两个字符串的最长公共子串”示例代码的小错误

---

docs/ds/avl.md

这份代码中的所有函数都经过了相应测试, 部分单元测试代码在[avltree.cpp](https://github.com/RIvance/algorithms-cpp/blob/master/data_structures/avltree_map.cpp)中
1. 注意有没有 typo

feat(ds/avl.md): add code example for avltree

---

docs/math/notation.md

fix(math/notation): \frac -> \dfrac

---

.mergify.yml

This change has been made by @CoelacanthusHex from https://mergify.com config editor.

ci(Mergify): defer to merge when require other PR

---

.github/CODEOWNERS
.github/workflows/build-pdf.yml

Reverts OI-wiki/OI-wiki#4052
We need logs. See https://github.com/OI-wiki/OI-wiki/runs/7628886153?check_suite_focus=true

Revert "ci: building pdfs silently"

---

docs/ds/code/li-chao-tree/li-chao-tree_1.cpp
docs/ds/li-chao-tree.md

[例题中给出的代码被 hack](https://www.luogu.com.cn/discuss/471593)
修改：在 `upd` 中判了线段编号，并且浮点数使用 `eps` 进行比较。
1. 注意有没有 typo

fix(ds/li-chao-tree.md)：修改错误的代码

---

docs/ds/code/binary-heap/binary-heap_1.cpp

fix(ds/code/binary-heap): typo

---

.github/workflows/build-pdf.yml
docs/math/number-theory/pollard-rho.md

miller-rabin-素性测试
1. 注意有没有 typo

fix: correct a link

---

docs/ds/pairing-heap.md

配对堆条目重构计划 Part 1
大幅重写了条目，改善（大概？）了一些表述，修正了目前的已知错误。
使用 svg 重制图片，加入复杂度证明等工作有待后续补充
1. 注意有没有 typo

refactor(ds/pairing-heap): 大规模重构条目

---

docs/basic/stl-sort.md

fix(basic/stl-sort.md): typo

---

docs/math/number-theory/lucas.md

修正字母混乱的情况
文档中字母 $M,p,q,\alpha$ 使用混乱，因此整理文档字母
1. 注意有没有 typo

fix lucas.md

---

docs/math/number-theory/sieve.md

fix(math/number-theory/sieve): 修复 Python 代码中错误的自增运算

---

docs/search/config/astar/astar_1.yml

为astar-1这道题添加了config文件。
添加了配置文件，以便于代码的分离和持续集成。

feat:add astar-1 config

---

docs/ds/ett.md
docs/math/number-theory/gcd.md

统一称呼
- [ x ] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

fix(math/number-theory/gcd.md): 统一称呼

---

docs/geometry/convex-hull.md

fix(convex-hull.md): 错误的习题排版与标题嵌套

---

docs/basic/prefix-sum.md
docs/ds/ett.md

feat(basic/prefix-sum): 更换例题

---

docs/dp/basic.md

fix(dp/basic.md): 修正最长不下降子序列代码错误

---

docs/string/kmp.md

fix(kmp): correct collapse syntax

---

docs/ds/code/kdt/kdt_1.cpp

KD树代码有误，建树时单节点要返回自身并对应地更新边界
1. 注意有没有 typo

fix(ds/code/kdt/kdt_1): 更正kd树代码错误

---

docs/string/ac-automaton.md

fix(ac-automaton): 修正一个格式语法错误

---

docs/intro/htc.md

revert an incorrect modification in #3055
fix a internal link

fix(intro/htc.md): incorrect modification in #3055

---

docs/ds/config/binary-heap/binary-heap_1.yml
docs/ds/config/block-list/block-list_1.yml
docs/ds/config/cartesian-tree/cartesian-tree_1.yml
docs/ds/config/decompose/decompose_1.yml
docs/ds/config/dividing/dividing_1.yml
docs/ds/config/ett/ett_1.yml
docs/ds/config/ett/ett_connectivity.yml
docs/ds/config/ett/ett_subtree_size.yml
docs/ds/config/kdt/kdt_1.yml
docs/ds/config/kdt/kdt_2.yml
docs/ds/config/kdt/kdt_3.yml
docs/ds/config/leftist-tree/leftist-tree_1.yml
docs/ds/config/leftist-tree/leftist-tree_2.yml
docs/ds/config/leftist-tree/leftist-tree_3.yml
docs/ds/config/li-chao-tree/li-chao-tree_1.yml
docs/ds/config/monotonous-queue/monotonous-queue_1.yml
docs/ds/config/monotonous-queue/monotonous-queue_2.yml
docs/ds/config/persistent-seg/persistent-seg_1.yml
docs/ds/config/persistent-trie/persistent-trie_1.yml
docs/ds/config/queue/queue_1.yml
docs/ds/config/seg-beats/seg-beats_1.yml
docs/ds/config/seg-beats/seg-beats_2.yml
docs/ds/config/seg-beats/seg-beats_3.yml
docs/ds/config/seg/seg_1.yml
docs/ds/config/seg/seg_2.yml
docs/ds/config/seg/seg_3.yml
docs/ds/config/sparse-table/sparse-table_1.yml
docs/ds/config/treap/treap_1.yml
docs/ds/config/tree-decompose/tree-decompose_1.yml

feat:add ds config

---

docs/geometry/config/3d/3d_1.yml
docs/geometry/config/pick/pick_1.yml

feat:add geometry config

---

docs/math/config/du/du_1.yml
docs/math/config/du/du_2.yml
docs/math/config/inclusion-exclusion-principle/inclusion-exclusion-principle_1.yml
docs/math/config/min-25/min-25_1.yml
docs/math/config/mobius/mobius_1.yml
docs/math/config/mobius/mobius_2.yml
docs/math/config/mobius/mobius_3.yml
docs/math/config/mobius/mobius_4.yml
docs/math/config/mobius/mobius_5.yml
docs/math/config/pollard-rho/pollard-rho_1.yml
docs/math/config/poly/fft/fft_1.yml
docs/math/config/poly/fft/fft_2.yml
docs/math/config/poly/fft/fft_3.yml
docs/math/config/poly/lagrange/lagrange_1.yml
docs/math/config/poly/lagrange/lagrange_2.yml
docs/math/config/poly/sqrt/sqrt_1.yml
docs/math/config/powerful-number/powerful-number_1.yml
docs/math/config/powerful-number/powerful-number_2.yml
docs/math/config/prime/prime_1.yml
docs/math/config/prime/prime_2.yml
docs/math/config/quick-pow/quick-pow_1.yml
docs/math/config/simplex/simplex_1.yml
docs/math/config/wilson/wilson_1.yml

feat:add math config

---

docs/misc/config/cdq-divide/cdq-divide_1.yml
docs/misc/config/cdq-divide/cdq-divide_2.yml
docs/misc/config/cdq-divide/cdq-divide_3.yml
docs/misc/config/cdq-divide/cdq-divide_4.yml
docs/misc/config/hill-climbing/hill-climbing_1.yml
docs/misc/config/hill-climbing/hill-climbing_2.yml
docs/misc/config/hoverline/hoverline_1.yml
docs/misc/config/hoverline/hoverline_2.yml
docs/misc/config/hoverline/hoverline_3.yml
docs/misc/config/mo-algo-with-bitset/mo-algo-with-bitset_1.yml
docs/misc/config/mo-algo/mo-algo_1.yml
docs/misc/config/modifiable-mo-algo/modifiable-mo-algo_1.yml
docs/misc/config/parallel-binsearch/parallel-binsearch_1.yml
docs/misc/config/rollback-mo-algo/rollback-mo-algo_1.yml
docs/misc/config/simulated-annealing/simulated-annealing_1.yml

feat:add misc config

---

docs/basic/config/binary/binary_1.yml
docs/basic/config/greedy/greedy_1.yml
docs/basic/config/prefix-sum/prefix-sum_1.yml
docs/basic/config/prefix-sum/prefix-sum_2.yml
docs/basic/config/prefix-sum/prefix-sum_3.yml
docs/basic/config/simulate/simulate_1.yml

feat:add basic config

---

docs/string/config/ac-automaton/ac-automaton_1.yml
docs/string/config/ac-automaton/ac-automaton_2.yml
docs/string/config/general-sam/general-sam_1.yml
docs/string/config/general-sam/general-sam_2.yml
docs/string/config/hash/hash_1.yml
docs/string/config/pam/pam_1.yml
docs/string/config/pam/pam_2.yml
docs/string/config/sa/sa_1.yml
docs/string/config/sa/sa_2.yml
docs/string/config/sa/sa_3.yml
docs/string/config/seq-automaton/seq-automaton_1.yml
docs/string/config/suffix-bst/suffix-bst_1.yml
docs/string/config/suffix-bst/suffix-bst_2.yml
docs/string/config/trie/trie_1.yml
docs/string/config/trie/trie_2.yml
docs/string/config/trie/trie_3.yml

feat:add string config

---

docs/dp/config/dag/dag_1.yml
docs/dp/config/dynamic/dynamic_1.yml
docs/dp/config/knapsack/knapsack_1.yml
docs/dp/config/knapsack/knapsack_2.yml
docs/dp/config/opt/monotonous-queue-stack/monotonous-queue-stack_1.yml
docs/dp/config/plug/plug_1.yml
docs/dp/config/plug/plug_2.yml
docs/dp/config/plug/plug_3.yml
docs/dp/config/plug/plug_4.yml
docs/dp/config/probability/probability_1.yml
docs/dp/config/probability/probability_2.yml
docs/dp/config/probability/probability_3.yml
docs/dp/config/state/state_1.yml
docs/dp/config/tree/tree_1.yml
docs/dp/config/tree/tree_2.yml
docs/dp/config/tree/tree_3.yml

feat:add dp config

---

docs/lang/class.md

fix(lang/class.md): 修复求向量内积的代码错误 (#4338)

---

docs/graph/graph-matching/bigraph-match.md

feat(graph/graph-matching/bigraph-match): 继承前人的二分图最大匹配加入描述

---

docs/math/number-theory/sieve.md

修复莫比乌斯函数实现的代码缩进问题  
issue: [#4341](https://github.com/OI-wiki/OI-wiki/issues/4341)

fix(docs/math/number-theory/sieve.md): 修复莫比乌斯函数实现的代码缩进问题

---

docs/ds/code/size-balanced-tree/SizeBalancedTreeMap.hpp
docs/ds/sbt.md

feat(ds/sbt): add size balanced tree

---

docs/ds/li-chao-tree.md

fix(ds/li-chao-tree): style fix

---

docs/string/trie.md

对比C++版本
```
if (!nex[p][c]) nex[p][c] = ++cnt;  // 如果没有，就添加结点
```
应为先cnt += 1，不然第一个节点会指向自身

fix(string/trie.md): python 版本实例 trie 代码

---

docs/math/number-theory/sieve.md

fix(math/number-theory/sieve): 修复莫比乌斯函数公式的错误

---

docs/graph/bfs.md

feat(bfs): add exercises

---

docs/tools/compiler.md

feat(tools/compiler): 添加更多编译器安装指南 

---

docs/ds/dsu.md

fix(dsu): correct `erase`

---

docs/dp/memo.md

fix(memo.md): 记忆化搜索  最长上升子序列错误

---

docs/contest/resources.md

fix(docs/contest/resources.md): 更改leetcode中文站域名

---

.github/workflows/config_test.yml
scripts/check-config.py

feat:add config CI

---

docs/ds/pairing-heap.md

- [*] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

fix(ds/pairing-heap.md): fix memory leak

---

docs/lang/java-pro.md

fix(lang/java-pro.md): 修正注释错误

---

docs/graph/shortest-path.md

'Djikstra' should be dijkstra.

fix(graph/shortest-path): corrected a mis-spelled word.

---

docs/math/number-theory/gcd.md

fix(math/gcd.md): added the missing comma

---

docs/search/code/astar/astar_1.cpp

fix(search/code/astar/astar_1.cpp): 65行注释错误

---

docs/math/young-tableau.md

fix(young-tableau.md):添加了Ferrers 图的内部链接

---

docs/ds/hash.md
docs/math/number-theory/inverse.md
docs/math/young-tableau.md

fix(docs/math/number-theory/inverse): 修复了乘法逆元中错误的python快速幂

---

docs/math/combinatorics/combination.md

fix(combination.md): typo

---

docs/math/probability/random-variable.md

fix(random-variable.md)：修正随机变量定义的一点错误

---

docs/tools/editor/clion.md

feat(clion.md): 增加Toolbox的用途

---

docs/lang/func.md

由于都是无返回值的代码示例，建议修改声明返回值为 void 类型。

fix(docs/lang/func.md): 修正声明与定义函数返回值不匹配

---

docs/graph/topo.md

refactor(topo): refactor dfs code

---

scripts/test.py

https://github.com/OI-wiki/OI-wiki/pull/4477#issuecomment-1336040039
运行结果：https://github.com/yusancky/OI-wiki/actions/runs/3607254899

fix(scripts/test.py): 使用 C++ 14 编译

---

docs/lang/optimizations.md

feat(lang/optimizations.md): add loop unswitching

---

docs/ds/llrbt.md

fix(llrbt.md): references

---

docs/misc/odt.md

feat(odt.md): 为misc/odt页面中的set添加链接

---

docs/basic/complexity.md

> - [ ] for some constant $k < 1$ and sufficiently large $n$。
> - [x] for some constant $c < 1$ and sufficiently large $n$。
> - [ ] 所以合并总共要花费 $a \left(\frac{n}{b}\right)$ 的时间
> - [x] 所以合并总共要花费 $a f\left(\frac{n}{b}\right)$ 的时间

fix(docs/basic/complexity):typo fix in master theorem proof

---

README.md
scripts/pre-build/install-theme-vendor.sh

This resolves #4169.
See https://github.com/OI-wiki/mkdocs-material/pull/37.

chore: remove Gitalk

---

docs/lang/optimizations.md

fix(lang/optimizations.md): fix typo

---

docs/math/poly/fft.md

fix(docs/math/poly/fft.md):typo fix in the Fourier Transform

---

docs/lang/java-pro.md

feat(lang/java-pro.md):增加ArrayDeque

---

docs/intro/hulu.md

fix(hulu.md): 修改公众号名称

---

.github/workflows/test.yml

我原本是想着减少时间来降低成本，很抱歉没有考虑到合并问题而给你们带来不便。
如果要使合并方便而又节省时间，也可以试试 https://github.com/marketplace/actions/changed-files 等 GitHub Marketplace 提供的 Actions。
ref: https://github.com/OI-wiki/OI-wiki/pull/4512#issuecomment-1354230355

fix(test.yml): 手工回退到文件的上一版本

---

docs/math/number-theory/quad-residue.md

feat(quad-residue.md): typo & 增加其他方法

---

docs/math/combinatorics/combination.md
docs/math/number-theory/periodic-continued-fraction.md

feat(math/combinatorics/combination.md)：新增二项式反演

---

docs/contest/common-mistakes.md

fix(contest/common-mistakes.md): 修复代码语法错误

---

docs/math/combinatorics/entringer.md
docs/math/number-theory/periodic-continued-fraction.md

fix(entringer.md): LaTeX 公式 & OEIS 外链

---

docs/lang/pb-ds/pq.md

fix(lang/pb-ds/pq): 修改列表项缩进

---

docs/dp/knapsack.md

feat(dp/knapsack): 优化部分代码格式

---

docs/contest/io.md
docs/ds/code/leafy-tree/leafy-tree_1.cpp
docs/ds/code/seg-beats/seg-beats_2.cpp
docs/graph/code/tree-divide/tree-divide_3.cpp
docs/graph/code/tree-hash/tree-hash_2.cpp
docs/math/poly/ntt.md
docs/misc/mo-algo-on-tree.md
docs/search/code/dlx/dlx_1.cpp
docs/search/code/dlx/dlx_2.cpp
docs/search/code/dlx/dlx_4.cpp

<https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0001r1.html>

refactor: remove deprecated use of the `register` keyword

---

mkdocs.yml

chore: update copyright

---

docs/math/bit.md

fix(math/bit.md):修改了会引发警告的代码

---

docs/math/game-theory/impartial-game.md
docs/math/game-theory/intro.md

fix: update author nickname

---

docs/string/kmp.md

fix(string/kmp.md)：修正python下find_occurences函数存在的一个错误

---

docs/math/complex.md

feat(complex.md)：修正了本页面中的所有的e和i

---

docs/math/poly/tri-func.md

feat(tri-func.md)：修正本页面e和i

---

docs/math/number-theory/mobius.md

fix(math/number-theory/moibus.md): add 狄利克雷卷积的链接

---

docs/graph/shortest-path.md

**我正在访问这个页面**
https://oi-wiki.org/graph/shortest-path
**我发现页面有这样的问题**
示例Python代码中存在冒号，是语法错误并已发PR修正

fix(graph/shortest-path.md): 代码修正 

---

docs/basic/tim-sort.md
mkdocs.yml

fix #2574 
文章作者为原作者，见#2637
署名已加在最前面

feat(tim-sort): tim排序 

---

docs/ds/seg.md

Fixes: #4665
<revert>（<seg.md>）: 删除群的部分

refactor(seg.md): 删除群的部分

---

docs/math/group-theory.md

refactor(group-theory.md): 改正链接格式

---

docs/string/kmp.md

fix(string/kmp.md): 修改拼写错误

---

docs/ds/splay.md

fix(ds/splay.md): 修复 Splay 实现代码中的错误 (#4696)

---

.github/workflows/build.yml
.github/workflows/check-format.yml
.github/workflows/config_test.yml
.github/workflows/test.yml

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

ci: bump actions

---

docs/lang/csl/container.md

fix(container.md): typo 关与 -> 关于

---

docs/string/sa.md

fix(string/sa.md): 修复重复声明编译错误

---

docs/math/number-theory/gcd.md

fix(math/number-theory/gcd.md): 纠正欧几里得算法的证明错误

---

mkdocs.yml

fix: remove extra js

---

docs/graph/connectivity.md

fix(graph/connectivity.md): 修改格式

---

docs/math/linear-algebra/basis.md

fix(basis.md): make bot happy

---

mkdocs.yml

https://github.com/OI-wiki/OI-wiki/pull/4727#issuecomment-1435832604

fix(graph/connectivity.md): 修改目录

---

docs/math/number-theory/wilson.md

fix (math/number-theory/wilson) : 修正 note 语句的格式错误。

fix (math/number-theory/wilson) : 修正 note 语句的格式错误。

---

docs/math/number-theory/inverse.md

fix(inverse.md): 修改了错误的拓展欧几里得法求 逆元 的 python代码段

---

docs/math/linear-algebra/product.md

fix( math/linear-algebra/product.md): fix typos

---

docs/ds/dsu.md
docs/ds/finger-tree.md
docs/geometry/triangulation.md
docs/graph/graph-matching/graph-match.md
docs/math/fourier-motzkin-elimination.md
docs/math/order-theory.md
docs/math/poly/ntt.md
docs/math/schreier-sims.md
docs/math/young-tableau.md
docs/misc/garsia-wachs.md

fix: footnotes

---

docs/tools/latex.md

fix(latex.md): 修复外链引用

---

docs/graph/graph-matching/code/general-match/general-match_1.cpp
docs/math/integral.md

fix(math/integral.md): fix some weird typos

---

docs/dp/knapsack.md

* fix(docs/dp/knapsack.md): fix the loop condition
* Update knapsack.md

fix(docs/dp/knapsack.md): fix the loop condition

---

docs/graph/virtual-tree.md

鉴于darkbzoj服务器较为缓慢，体验较差，并且需要梯子。故将例题的来源链接变为洛谷的链接

fix(virtual-tree.md)：将例题链接由darkbzoj迁移到洛谷

---

docs/misc/expression.md

feat(misc/expression.md): 增加一些参考链接

---

docs/ds/monotonous-queue.md

[《NOI 大纲（2023 年修订版）》](https://www.noi.cn/upload/resources/file/2023/03/15/1fa58eac9c412e01ce3c89c761058a43.pdf) 已将「有序队列」改为「单调队列」。

fix(monotonous-queue.md)：删除页面开头的注意

---

docs/basic/enumerate.md

本文python代码不规范之处：
1. range函数传递多余参数
2. if后面添加多余括号
3. 不会使用自增运算符
4. 混合使用2空格和4空格缩进

fix(basic/enumerate.md): 修正代码风格

---

docs/basic/complexity.md

fix: convert the fullwidth character `+` to halfwidth

---

docs/intro/faq.md

fix(intro/faq.md): 添加标点符号

---

docs/tools/cmd.md

fix(cmd.md): typo

---

docs/dp/knapsack.md

fix(dp/knapsack.md): typo

---

docs/search/dfs.md

feat(search/dfs.md): 添加 Java 实现

---

docs/basic/quick-sort.md

fix(quick-sort.md)：修正三路快排C++代码的注释错误

---

.github/workflows/check-quotes.yml

ci(check-quotes): 增加引号检查

---

docs/ds/sbt.md

fix(sbt.md): typo

---

docs/_redirects
docs/math/berlekamp-massey.md
docs/math/number-theory/quad-residue.md
docs/math/poly/linear-recurrence.md
mkdocs.yml

将常系数齐次线性递推的文章移至 /math/poly 目录下
https://github.com/OI-wiki/OI-wiki/pull/4611#issuecomment-1380486042

fix(linear-recurrence.md): 移至 /math/poly 目录

---

docs/contest/io.md
docs/contest/oi.md
docs/math/linear-programming.md

fix(docs/contest/oi.md, docs/contest/io.md, docs/math/linear-programming.md): 修复由于更改GitHub用户名引发的author字段错误

---

docs/math/simplex.md

fix(math/simplex.md) 对偶定理一节中 y 误写成 t

---

docs/lang/pb-ds/index.md

feat(index.md): 增添一部分pb_ds库的实例加以说明

---

Pipfile.lock

This reverts commit 1e766f24c78be13caa70ce0182d4c289b239a96f.

revert: "chore(deps): bump pymdown-extensions from 9.9 to 10.0 (#4882)"

---

docs/dp/plug.md

添加一些插头 dp 章节的习题，并在章节注记中介绍一些和一笔画问题相关的解谜游戏。
添加一些插头 dp 章节的习题，并在章节注记中介绍一些和一笔画问题相关的解谜游戏。

feat(dp/plug.md): 添加插头 dp 章节的习题

---

docs/graph/euler.md

feat(graph/euler.md): 添加欧拉图章节的习题

---

docs/graph/flow/max-flow.md

见 https://github.com/OI-wiki/gitment/discussions/736#discussioncomment-4305393

fix(graph/flow/max-flow.md): 修复 HLPP 代码

---

docs/intro/symbol.md

feat(symbol.md): 添加指向数学符号表源代码的链接

---

docs/contest/common-tricks.md

https://github.com/OI-wiki/OI-wiki/pull/4809#issuecomment-1491436122

refactor(common-tricks.md): 移除 unroll 和 reassociate 相关内容

---

docs/dp/number.md

fix(number): 删除多余代码

---

docs/math/number-theory/primitive-root.md

fix(math/number-theory/primitive-root.md): 添加原根部分符号定义(#4860)

---

docs/graph/virtual-tree.md

fix(virtual-tree.md):将代码中的unque改成unique

---

.github/workflows/build-pdf.yml

报错：tex capacity exceeded sorry main memory size=50000
参考 https://tex.stackexchange.com/a/7954 进行了修改
脚本由gpt编写 https://github.com/OI-wiki/OI-Wiki-export/blob/master/oi-wiki-export/increase-mem-limit.py

ci: fix latex build

---

docs/string/hash.md

https://github.com/OI-wiki/gitment/discussions/1161#discussioncomment-6242617

fix(hash.md): overflow

---

scripts/post-build/minify-html/minify-html.sh

chore: update minify-html to v0.11.1

---

docs/ds/rbtree.md

fix(rbtree.md): delete case 4

---

docs/graph/block-forest.md

feat(graph/block-forest): 添加作者（author）字段

---

docs/tools/editor/devcpp.md

小熊猫C++是使用qt5开发的轻量级跨平台C/C++ IDE。界面上类似Dev-CPP
resolve #4963

feat(editor/devcpp.md): 增加关于小熊猫 C++ 的介绍

---

docs/math/number-theory/fermat.md

fix(math/number-theory/fermat.md): 修改一个打字错误

---

docs/graph/shortest-path.md

fix(graph/shortest-path.md): fix python init value

---

docs/graph/save.md
docs/graph/shortest-path.md
docs/string/trie.md

fix: python class variable -> instance variable

---

docs/ds/hash.md
docs/graph/save.md

fix: Python `list of class instance * number`

---

docs/geometry/rotating-calipers.md
docs/graph/cut.md
docs/graph/prufer.md
docs/graph/scc.md
docs/graph/shortest-path.md

fix: meaningless Python `[] * N`

---

docs/misc/modifiable-mo-algo.md

feat(modifiable-mo-algo):改进 LaTeX

---

docs/tools/wsl.md

fix(tools/wsl.md): 修正 WSL 文档的错误，语言书面化

---

docs/misc/parallel-binsearch.md

fix(parallel-binsearch.md)：修正构造单调性序列中的错误注释

---

docs/graph/hld.md

1. "DFN 序" -> "DFS 序"。
2. LCA 由 LaTeX 公式改为指向 LCA 介绍的链接。
3. 更正模板题名。

fix(docs/graph/hld.md): 修正文本错误

---

docs/math/number-theory/continued-fraction.md

fix continued-fraction.md: 修正生草翻译（竞争性编程）

---

docs/ds/code/li-chao-tree/li-chao-tree_1.cpp
docs/ds/li-chao-tree.md

原来的实现可能会在 l == r 且 u < v 时继续递归并导致错误，详见 #5008

fix(li-chao-tree): 修正李超树 upd 函数实现

---

docs/tools/compiler.md

fix(compiler.md): typo

---

docs/tools/oj-tool.md

CP Editor 已经在 /tools/editor/cpeditor/ 下了，/tools/oj-tool/ 下的为重复内容。

refactor(oj-tool.md): remove CP Editor

---

.github/ISSUE_TEMPLATE/request-for-comment.yml

feat: Issue template for raising RFC

---

docs/lang/csl/algorithm.md

`prev_permutation` 的直接应用：[ABC276 C](https://atcoder.jp/contests/abc276/tasks/abc276_c)

feat(docs/lang/csl/algorithm.md): 添加 prev_permutation 介绍

---

docs/math/number-theory/mobius.md

fix(mobius): 移除错误算式

---

docs/graph/dominator-tree.md

https://github.com/OI-wiki/gitment/discussions/1211

fix(dominator-tree.md): 修改支配树中的两处错误

---

docs/lang/pb-ds/pq.md

fix(pq.md): typo

---

docs/misc/random.md

fix(random.md): 使用 cppreference 链接替换原列表

---

docs/math/number-theory/powerful-number.md

resolve https://github.com/OI-wiki/gitment/discussions/1005#discussioncomment-4306385

fix(powerful-number.md): 修正公式错误 \textit -> \operatorname, \cdot

---

docs/tools/editor/vscode.md

fix(vscode.md): 插件 -> 扩展

---

docs/misc/garsia-wachs.md

fix(garsia-wachs.md): typo

---

docs/graph/graph-matching/graph-match.md

feat(graph-match.md): 增加翻译

---

docs/basic/insertion-sort.md

- 修复 [折半插入排序示例代码](https://github.com/OI-wiki/OI-wiki/blob/master/docs/basic/insertion-sort.md?plain=1#L91) 中已知`bug`

fix(docs/basic/insertion-sort.md): 折半插入排序示例代码问题修复 #1

---

docs/graph/flow/max-flow.md

https://github.com/OI-wiki/gitment/discussions/736#discussioncomment-6718254

fix(max-flow): 修复 HLPP 代码

---

docs/tools/oj-tool.md

resolve #5015 
添加了插件 ac-predictor ，用于预测 atcoder 比赛的 rating 变化。

feat(tools/oj-tool.md): 添加 ac-predictor

---

docs/lang/optimizations.md

fix #5092 
修复了示例代码与参考链接与文字不匹配的问题

fix(lang/optimizations.md) fix SCEV example (#5092)

---

scripts/netlify/install-python.sh

fix: netlify build error on Python installation

---

docs/math/permutation.md

resolve https://github.com/OI-wiki/gitment/discussions/1208#discussioncomment-6082241

fix(permutation.md): composition

---

docs/intro/symbol.md

fix(symbol.md)：修正上升阶乘幂的符号错误

---

docs/graph/tree-basic.md

fix(tree-basic): 修改完美二叉树的定义

---

docs/tools/wsl.md

fix(docs/tools/wsl.md): 使用更严谨的表述

---

docs/math/number-theory/euler.md

fix(euler.md): python sqrt() 应为 math.sqrt()

---

docs/math/number-theory/meissel-lehmer.md

fix https://github.com/OI-wiki/gitment/discussions/1217#discussioncomment-6883967

fix(meissel-lehmer.md): LaTeX

---

docs/math/combinatorics/fibonacci.md
docs/math/number-theory/lift-the-exponent.md
mkdocs.yml

原 #4936 的一部分
1. 将原页面「升幂定理」重命名为「升幂引理」
2. 按知识点的依赖关系，将升幂引理的目录顺序提至 Wilson 定理之前
3. 因为原内容错漏较多（see #4937），故重写了整个页面，以完善升幂引理的内容和证明

refactor: 重写升幂引理

---

docs/math/number-theory/discrete-logarithm.md

原 #4936 的一部分
1.  移除不必要的复变函数内容
2.  修正「离散对数是多值函数」的错误表述
3.  补充离散对数的若干性质
4.  格式修正

refactor(discrete-logarithm.md): 重写离散对数

---

docs/math/number-theory/wilson.md

原 #4936 的一部分
1.  重写了 Wilson 定理的证明
2.  修正若干公式的写法
3.  调整了内容布局

refactor(wilson.md): 重写 Wilson 定理

---

docs/math/poly/fft.md

fix(fft.md): term DFT -> DTFT

---

docs/tools/special-judge.md

syzoj/testlib 已添加针对交互模式的 patch，这个提交将其补充到 OI Wiki 上。

feat(tools/special-judge.md): 添加新的 testlib patch 地址

---

docs/geometry/nearest-points.md

fix(nearest-points.md): broken link

---

.github/workflows/build.yml
scripts/post-build/redirect/check-redirects.py
scripts/post-build/redirect/generate-redirects.py

ci: check that _redirects contain all old links

---

docs/misc/mo-algo.md

fix(mo-algo.md): 修改错误的莫队算法代码

---

.github/workflows/incrementally-build-pdf.yml

这是对应 https://github.com/OI-wiki/OI-Wiki-export/pull/40 的增量 PDF 导出 workflow PR。
使用了 fkirc/skip-duplicate-actions@v5 以避免高频率提交 PR commit 导致的 race 情况。

ci: workflow for incremental pdf build

---

docs/math/number-theory/sieve.md

fix(sieve.md): typo

---

docs/ds/seg.md
docs/lang/java-pro.md

fix: 修复两处 details 缩进问题

---

docs/dp/knapsack.md

fix(dp/knapsack): 改正多重背包python代码

---

docs/math/number-theory/primitive-root.md

fix(primitive-root.md): adjust content

---

docs/lang/java-pro.md

fix:
文件名：docs/lang/java-pro.md
1.<初始化>栏目下：<c 的值为30>改为<b 的值为30>
2.<继承>:<对所有人类开放>改为<对所有类开放>

fix(lang/java-pro): fix typos

---

docs/intro/faq.md

fix(intro/faq): 将GoogleHosts替换为Github520 & 替换失效的FastGit为Gitclone

---

docs/lang/csl/iterator.md

feat(iterator.md): contiguous iterator & link to cppreference.com

---

docs/lang/csl/algorithm.md

fix(csl/algorithm): delete a wrong function

---

docs/graph/dominator-tree.md

fix(dominator-tree.md): 修改支配树DAG特例中代码的细节错误

---

docs/graph/mod-shortest-path.md

feat(graph/mod-shortest-path): 新增一道习题

---

docs/graph/save.md

fix(graph/save): remove extra end code block mark in sample code

---

docs/misc/code/modifiable-mo-algo/modifiable-mo-algo_1.cpp
docs/misc/modifiable-mo-algo.md

修改了带修改莫队例题 -> **[国家集训队] 数颜色 / 维护队列**的代码，原来 Wiki 上的代码无法通过题目，现更改为可以通过题目的代码，代码提供者 Luogu 号（即我本人）：[lovely_codingcow](https://www.luogu.com.cn/user/765847), Luogu 提交记录：[https://www.luogu.com.cn/record/129539736](https://www.luogu.com.cn/record/129539736)。该代码已经按照 oi-wiki 所指定的格式进行格式化，望尽快通过，避免 OIer 参考错误的代码影响训练。

fix(modifiable-mo-algo): 修改了带修改莫队例题的代码

---

docs/graph/bfs.md

fix(graph/bfs): 修正python版代码初始化bug

---

docs/graph/dfs.md

`dfs`的`python`代码将对 `i` 的初始化放在了循环内，与所期望行为不同。修正了python代码的初始化。

fix(graph/dfs): 修正python实现的初始化bug

---

docs/basic/tournament-sort.md

fix(basic/tournament-sort) 修正锦标赛排序的python代码

---

docs/basic/divide-and-conquer.md

fix(divide-and-conquer): fix broken html

---

docs/lang/python.md

fix(lang/python): fix typo

---

docs/dp/interval.md

1. 原代码中，没有对 `i` 的范围依据长度进行限制，同样也没对 `j` 进行限制，使得 `j` 必定会越界。修正了该部分内容，使得其处在正确的范围内。
2. 原代码中，长度从1开始，但并无意义。修改为从2开始。
3. 原代码中，python代码并没有每次将 `k` 初始化为 `i`。修改为`range`。
4. 原代码中由于没对 `j` 限制， 需要对 `k` 进行限制， 但由于增加了对 `j` 的限制，使得 `k` 只需满足 `k < j` 即可。

fix(dp/interval): 修正区间dp的代码bug

---

docs/lang/file-op.md

fix(file-op.md): fix a typo in the example of `fopen()` usage

---

docs/ds/code/sparse-table/sparse-table_2.hpp

fix(ds/code/sparse-table_2.hpp): ST 表查询函数有误

---

docs/basic/code/binary/binary_1.py

按照 [#5197](https://github.com/OI-wiki/OI-wiki/issues/5197) 的要求修正代码

fix(basic/code/binary/binary_1.py): 修正三分法 python 代码 (#5197)

---

.github/workflows/build-pdf-typst.yml

feat(ci/typst): 为 CI 流程添加 Typst PDF 导出测试

---

.github/workflows/build-pdf-typst.yml

ci: add name for typst build

---

.github/workflows/build-pdf.yml
.github/workflows/incrementally-build-pdf.yml

ci: only run full latex build on master

---

docs/math/complex.md
docs/math/number-theory/sieve.md
docs/math/poly/shift.md

fix: no more \over

---

.github/workflows/build-pdf-typst.yml
docs/graph/rings-count.md

chore(deps): update to typst v0.9.0

---

.github/workflows/incrementally-build-pdf.yml

ci: remove incremental latex filter

---

docs/intro/format.md

fix(format.md): remove outdated link

---

docs/ds/bst.md

fix(docs/ds/bst.md): 去除“插入一个元素”部分多余的一行描述(#5279)

---

docs/graph/graph-matching/graph-match.md

参照前文，将“maximal matching”翻译为“极大匹配”。
[PR #5030](https://github.com/OI-wiki/OI-wiki/pull/5030) 翻译了前文中的“maximal matching”，但没有修改下面小标题中的文字。

fix(graph/graph-matching/graph-match.md) 补充翻译

---

docs/graph/lca.md

fix(graph/lca): 调整随机树情况下时间复杂度的表达

---

docs/graph/virtual-tree.md

fix(virtual-tree.md): 完善引入部分例题题面

---

docs/graph/mdst.md

该网页 https://oi-wiki.org/graph/mdst/#%E4%BE%8B%E9%A2%98 中的题目链接失效。
网站中的 cf266D 指向的是 codeforce.ml，目前已经失效，我在 PR 中将其修改为指向 codeforce.com

fix(mdst.md): URL of cf266D

---

.github/workflows/build-pdf-typst.yml

ci(typst): update to typst v0.10.0, texmath v0.12.8.6

---

docs/basic/quick-sort.md

fix(basic/quick-sort.md): 补全括号

---

docs/lang/csl/index.md

fix(index.md): update C++ std version of ICPC

---

docs/math/combinatorics/entringer.md

fix(entringer.md): formula

---

docs/graph/mst.md

在最小生成树和询问点的最小边权 $\geq p$ 的节点。
=>
在最大生成树中和询问点的路径上最小边权 $> p$ 的节点。

fix(graph/mst): 修正了 NOI 2018 归程做法的笔误

---

docs/tools/latex.md

给阅读资料添加无序列表；  
添加该页面对应的 github 源代码页面的链接，顺便微调表述。

feat(tools/latex.md): 添加无序列表与源代码页面链接

---

.github/workflows/build-pdf-typst.yml

ref: https://github.com/OI-wiki/OI-Wiki-export/pull/61

ci(typst): remove texmath

---

.github/workflows/check-quotes.yml

- https://github.com/OI-wiki/OI-wiki/pull/5329#discussion_r1436228659
- https://github.com/reviewdog/action-suggester/blob/master/README.md#required-permissions

ci(check-quotes): 修正权限设定

---

.github/workflows/check-quotes.yml

https://github.com/OI-wiki/OI-wiki/pull/5333#issuecomment-1869537118

revert(check-quotes.yml): revert to #4845

---

docs/math/combinatorics/inclusion-exclusion-principle.md

feat(inclusion-exclusion-principle.md): 添加容斥原理习题

---

docs/graph/dfs.md

feat(graph/dfs.md): 为DFS增加邻接表实现和部分超链接

---

mkdocs.yml

chore: hello, 2024

---

docs/math/combinatorics/graph-enumeration.md

feat(graph-enumeration.md): 添加图论计数习题

---

docs/graph/code/lca/lca_tarjan.cpp

1. 在最近公共祖先的内容中，提到算法的复杂度为O(m\alpha (m+n, n)+n)那么对应的实现应该使用路径压缩，因此添加路径压缩。
2. 在tarjan函数内部已经进行parent[u] = u;操作，不需要进行额外的init，因此删除init函数及其调用。

fix(graph/code/lca/lca_tarjan.cpp): 删除冗余初始化，增加路径压缩

---

docs/graph/shortest-path.md

原始代码的实现为O(n(n+m))，因此在文中添加说明，同时给出O(nm)的实现。

fix(graph/shortest-path.md): 修改Bellman-Ford实现 使其复杂度严格为O(nm)

---

docs/math/number-theory/sieve.md

fix(number-theory/sieve): 修正埃氏筛代码

---

docs/tools/editor/clion.md

fix(clion.md): toolchain installation

---

docs/math/number-theory/pollard-rho.md

fix(pollard-rho.md): codeforces.ml -> codeforces.com

---

package.json
yarn.lock

use remark-tabbed v0.1.0 rather than git dependency

---

docs/math/number-theory/prime.md

Ref: [Miller_Rabin的复杂度 - 洛谷](https://www.luogu.com.cn/discuss/764873)

fix(math/number-theory/prime): 修改 Miller-Rabbin 复杂度部分

---

docs/math/number-theory/sqrt-decomposition.md

fix(sqrt-decomposition): typo

---

docs/lang/optimizations.md

修复两处「索引变量强度削减 (IndVars) 」部分中的代码错误：多次定义同意变量、未加分号，并修复了[该评论](https://github.com/OI-wiki/gitment/discussions/1008#discussioncomment-4716940)提到的问题。

fix(lang/optimizations.md): fixed wrong codes.

---

docs/graph/dominator-tree.md

fix(dominator-tree.md): 修改引理 9 的证明

---

docs/math/number-theory/fermat.md

fix(number-theory/fermat.md): 将 Ai 的上界从 n 修正为 p-1

---

docs/ds/wblt.md

Fixes: 01654c276f7a ("(feat(ds/wblt.md): 改善 WBLT 页面内容 (#5290)")
Fixes #5388

fix(ds/wblt): Fix typo in definition of rho_3 and gamma_3 (#5388)

---

docs/intro/format.md

[原链接](https://www.nppa.gov.cn/nppa/contents/805/102791.shtml)失效，由于[Wayback Machine](https://web.archive.org/)没有存储规范正文PDF，将其替换为[平替链接](https://std.samr.gov.cn/hb/search/stdHBDetailed?id=8B1827F23645BB19E05397BE0A0AB44A)。

fix(intro/format.md): 重定向失效链接

---

.github/workflows/Gitee.yml
.github/workflows/build-authors-cache.yml
.github/workflows/build-pdf-typst.yml
.github/workflows/build-pdf.yml
.github/workflows/build.yml
.github/workflows/celebration.yml
.github/workflows/check-characters.yml
.github/workflows/check-format.yml
.github/workflows/check-quotes.yml
.github/workflows/check-scripts.yml
.github/workflows/config_test.yml
.github/workflows/incrementally-build-pdf.yml
.github/workflows/pr-stale.yml
.github/workflows/test.yml

很疑惑，为什么当时 #4701 没有改全（
但怎么说要干掉 Node 12 已经过去半年了，已经在干 Node 16 了，它还能跑（

ci: bump actions to latest version

---

scripts/celebration.py

chore(celebration): also celebrate on multiple of 5k

---

.github/workflows/build-pdf-typst.yml
.github/workflows/build-pdf.yml

ci(build-pdf-typst): auto fetch latest deps

---

docs/basic/code/simulate/simulate_1.java
docs/basic/simulate.md

feat(basic/simulate): 增加Java代码

---

docs/math/number-theory/du.md

fix https://github.com/OI-wiki/gitment/discussions/827#discussioncomment-8528743

fix(du.md): typo

---

docs/lang/python.md

fix(lang/python): fix incorrect type conversion

---

docs/basic/enumerate.md

met长度应为2*MAXN+1而不是2*MAXN
修改met = MAXN*2 为met = MAXN*2+1

fix(basic/enumerate): met 数组开小了

---

.github/workflows/build-pdf-typst.yml

ci(build-pdf-typst): use typst v0.10.0

---

docs/math/combinatorics/code/graph-enumeration/graph-enumeration_2.cpp
docs/math/number-theory/gcd.md

see <https://stackoverflow.com/questions/68772236/what-is-the-difference-between-std-gcd-and-stdgcd>

fix: no `std::__gcd`

---

docs/lang/var.md

feat(var.md): warning about `__int128_t`

---

docs/geometry/distance.md

feat(geometry/distance.md): 更改 L_m 距离为闵可夫斯基距离且增加闵可夫斯基距离中对切比雪夫距离的描述

---

.github/workflows/build-pdf-typst.yml

fix: bump typst to v0.11.0-rc1 and remove verbose

---

docs/graph/virtual-tree.md

the weight the graph has some trouble

fix(virtual-tree.md): typo

---

docs/ds/treap.md

feat(ds/treap.md): 将空白注释补全

---

docs/lang/optimizations.md

fix(optimizations.md): typo

---

.github/workflows/build-pdf-typst.yml

chore: upgrade to typst v0.11.0

---

docs/math/number-theory/quad-residue.md

fix(quad-residue.md): typo

---

docs/lang/optimizations.md

fix(optimizations.md): 把 `## 参考资料与注释` 移至文末

---

.github/workflows/build-pdf.yml
.github/workflows/incrementally-build-pdf.yml

fix: roboto mono

---

docs/graph/shortest-path.md
docs/lang/csl/bitset.md

fix(shortest-path.md): Python code

---

docs/math/number-theory/gcd.md

feat(math/number-theory/gcd.md): 修改一处应使用 LaTeX 但未使用处

---

docs/ds/fenwick.md

fix: 修改树状数组求kth最值中python代码无法跳出循环问题，以及错别字修改。

fix(fenwick.md): 修正树状数组求kth最值中的python代码

---

docs/math/number-theory/gcd.md

fix(gcd.md)：将高精度 gcd 枚举 2 的幂因子抽象为计算 countr_zero 并给出与欧几里得算法相比速度的结论

---

docs/basic/binary.md
docs/math/binary-set.md
docs/string/sa.md

fix(basic/binary.md, math/binary-set.md, string/sa.md) 将Uva 修改为 UVa。(#5508 )

fix(basic/binary.md, math/binary-set.md, string/sa.md) 将Uva 修改为 UVa

---

docs/ds/splay.md

fix(ds/splay.md): 修正 splay 函数

---

docs/graph/kth-path.md

k 短路的可持久化可并堆实现有一些问题 导致该代码使用的是大根堆
这个PR修改了该代码
详见[issue](https://github.com/OI-wiki/OI-wiki/issues/5497)

fix(graph/kth-path.md): 修正 k 短路的可持久化可并堆算法的 Bug

---

docs/graph/cut.md

feat(graph/cut.md): 修正伪代码中的笔误

---

docs/math/number-theory/sqrt-decomposition.md

feat(math/number-theory/sqrt-decomposition.md): 修正伪代码格式

---

docs/lang/helloworld.md

给出一个新的写法，与下一条目保持一致，增加注释（#5541）

feat(lang/helloworld.md)增加另一种代码

---

docs/string/ac-automaton.md

感觉很多地方的 Python 实现都是照着 C++ 版本无脑改写的，明显没有经过测试，有不少十分低级的错误。这里的几个问题我修复了一下。

fix(docs/string/ac-automaton.md): 修正 Python 实现

---

docs/math/number-theory/meissel-lehmer.md

fix(math/number-theory/meissel-lehmer.md): typo

---

docs/ds/splay.md

已经有多个关于这个错误的PR，但是都未被合并且 Closed，请求添加。

fix(ds/splay.md)：在查找排名时对于Splay中不存在的数进行判断。

---

docs/basic/code/prefix-sum/prefix-sum_2.cpp

feat(basic/code/prefix-sum/prefix-sum_2.cpp): 修正参考代码

---

docs/math/number-theory/stern-brocot.md

fix(docs/math/number-theory/stern-brocot.md): fix func ident, format using ruff

---

docs/math/number-theory/euler-totient.md

fix(euler-totient.md): typo

---

docs/string/sa.md

fix(string/sa): SA 常数优化勘误 (#5585)

---

docs/math/number-theory/primitive-root.md

fix(math/number-theory): typo

---

docs/string/sa.md

下面的读入是 `scanf`。
非常抱歉之前没有表明清楚自己的意思。

fix(sa.md): 移除代码中的关闭同步流

---

.github/workflows/check-format.yml

ci: run bot check in ci

---

docs/ds/code/leftist-tree/leftist-tree_1.cpp

fix(leftist-tree_1.cpp): MLE in C++20

---

docs/math/number-theory/sieve.md

fix(math/sieve.md): 改正了原文中对“位级压缩”的误解

---

docs/geometry/code/scanning/scanning_1.cpp

fix(geometry/scanning): 统一树状数组实现与我另两个代码相同

---

docs/ds/code/leftist-tree/leftist-tree_1.cpp
docs/ds/code/leftist-tree/leftist-tree_2.cpp
docs/ds/code/leftist-tree/leftist-tree_3.cpp
docs/ds/leftist-tree.md

参考资料：
- [CSC 378: Data Structures and Algorithm Analysis - LEFTIST TREES](https://www.dgp.toronto.edu/public_user/JamesStewart/378notes/10leftist/)
- [Skew Heap - Wikipedia](https://en.wikipedia.org/wiki/Skew_heap)
代码测试
1. [LOJ 188](https://loj.ac/s/2070186)
2. [LOJ 2107](https://loj.ac/s/2070150)
3. [LOJ 2441](https://loj.ac/s/2070166)

refact(ds/leftist-tree): refact defination and codes

---

.github/CODEOWNERS
README.md
mkdocs.yml

据我所知这个已经过时且不维护了。 cc @CoelacanthusHex

chore: hide docker build

---

docs/tools/editor/devcpp.md

feat(tools/editor/devcpp.md): 增加快捷键

---

docs/intro/format.md

fix: remove unsupported details usage

---

docs/lang/lambda.md

fix(lang/lambda): fix typo

---

docs/math/poly/fwt.md

fix(math/poly/fwt.md): fwt线性变换部分bug修复

---

docs/tools/compiler.md

feat(tools/compiler.md): 添加介绍 PortableBuildTools & 润色表达

---

docs/math/number-theory/basic.md

fix https://github.com/OI-wiki/gitment/discussions/986#discussioncomment-9770410

fix(basic.md): typo

---

docs/math/linear-algebra/linear-mapping.md

fix(linear-mapping.md): 更新了已经失效的链接

---

.github/workflows/build-pdf-typst.yml
.github/workflows/build-pdf.yml
.github/workflows/check-format.yml
.github/workflows/incrementally-build-pdf.yml

如果镜像用最新的话会报错，所以和 OI-Wiki/latex-action 一样将 `docker_image` 锁在 `20220801` 了。

chore(ci): various update

---

docs/math/poly/fwt.md

fix https://github.com/OI-wiki/gitment/discussions/672#discussioncomment-9825866

fix(fwt.md): typo

---

docs/ds/seg.md

线段树章节下的部分代码存在纰漏，使用额外数组储存是否修改值时更新节点应该同时更新该额外数组。问题出现在[线段树 - OI Wiki](https://oi-wiki.org/ds/seg/#%E5%AE%9E%E7%8E%B0_2)的最后一个代码片段。
其中，d数组用来存储线段树节点的值，b数组用于存储懒更新后的期望值，v数组用来存储对应下标的节点是否需要更新。但是在更新节点时，示例代码并没有把当前节点标记为需要更新：
```
void update(int l, int r, int c, int s, int t, int p) {
if (l <= s && t <= r) {
d[p] = (t - s + 1) * c, b[p] = c; // 此处同样需要将v[p]置为1，否则更新不会populate到其子节点
return;
}
int m = s + ((t - s) >> 1);
// 额外数组储存是否修改值
if (v[p]) {
d[p * 2] = b[p] * (m - s + 1), d[p * 2 + 1] = b[p] * (t - m);
b[p * 2] = b[p * 2 + 1] = b[p];
v[p * 2] = v[p * 2 + 1] = 1;
v[p] = 0;
}
if (l <= m) update(l, r, c, s, m, p * 2);
if (r > m) update(l, r, c, m + 1, t, p * 2 + 1);
d[p] = d[p * 2] + d[p * 2 + 1];
}
```
测试代码如下：
```
d = [0] * 1000
b = [0] * 1000
v = [0] * 1000
a = [1, 1, 1, 1]
def build(s, t, p):
if s == …
```

fix(ds/seg.md): 修线段树中“线段树的区间修改与懒惰标记”部分的示例代码

---

netlify.toml
package.json
scripts/netlify/build.sh
yarn.lock

security: update octokit

---

docs/search/code/dlx/dlx_1.cpp

chore: remove unused global variable in DLX

---

docs/contest/io.md

fix(io.md): link description

---

docs/math/linear-algebra/linear-mapping.md

fix https://github.com/OI-wiki/gitment/discussions/1212#discussioncomment-9944532

fix(linear-mapping.md): typo

---

docs/math/number-theory/basic.md

此处公式错将`bc`写成`ba`
例如 $a=5,b=2,c=6$ 时：
$[a, b, c]=30, [ab,bc,ca]=[10,12,30]=60,[a,b][b,c][c,a]=10\times6\times30$
而
$[ab,ba,ca]=[10,10,30]=30$ 不满足相等的条件。

fix(basic.md): 修改笔误

---

Pipfile
Pipfile.lock
docs/_static/css/offset-inject-debug.css
docs/math/order-theory.md
mkdocs.yml

此 PR 添加了 `python-markdown-document-offsets-injection-extesion` 作为 `python-markdown` 的编译器插件，这是为了实现站点划词评论的前置步骤。
除此之外，还添加了 `debug.css` 用以评估拓展生成的数据准确性，在启用该 CSS 时需要确保同时启用上述编译器插件 `debug mode`。

feat: add python-markdown-document-offsets-injection-extesion

---

docs/math/poly/dgf.md

- [-] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

fix(math/poly):修正“积性函数的逆元也是积性函数”的证明过程

---

docs/tools/editor/clion.md

fix(tools/editor/clion): misc format fix

---

docs/math/order-theory.md

fix(order-theory.md): typo

---

docs/lang/python.md

fix(python): typo and redundant semicolon

---

docs/ds/aa-tree.md

feat(ds/aa-tree): 增加 aa-tree 可视化等参考链接

---

docs/graph/dsu-on-tree.md

feat(graph/dsu-on-tree): typo

---

docs/graph/dominator-tree.md

feat(graph/dominator-tree.md): 删除多余右括号

---

scripts/post-build/html-postprocess.ts
scripts/post-build/math/task-handler.ts

fix: ci post process cannot run in windows

---

docs/graph/virtual-tree.md

1. `dfn 序` -> `dfs 序`
2. 删除未使用的 `bool valid[maxn]`

fix(docs/graph/virtual-tree.md): 删除无用定义 & 修正注释表述

---

docs/contest/common-mistakes.md

由于我先前已经对这个页面进行过更改，所以没有添加用户名。
其案例为我同学在 CSP-J2023 爆零的真实案例，仅为警示后人。

feat(contest/ommon-mistakes.md)：add more problems which will make you get WA.

---

docs/ds/code/seg/seg_4.hpp
docs/ds/code/seg/seg_5.hpp

fix(ds/seg): C++ 区间修改参数应使用模板类型

---

docs/geometry/rotating-calipers.md

fix(geometry/rotating-calipers.md): fix bug in code

---

.github/workflows/lint_pr_title.yml

feat(ci): lint pr title

---

docs/misc/parallel-binsearch.md

1. 修复了 `vector<int>` 应改为 `vector<Query>` 这一确定笔误。
2. 根据代码和上下文我推断作者的 `check` 函数其实是有值域参数的，否则会出错（例如 $a=1,2,3,4,5$，查询第 $5$ 大时会输出 $4$）。

fix(misc/parallel-binsearch): 代码和注释

---

docs/ds/bst.md

fix(ds/bst.md): 修改二叉排序树删除算法的考虑不周之处

---

docs/misc/odt.md

feat(misc/odt.md): 添加珂朵莉树模版例题

---

docs/dp/interval.md

fix(dp/interval.md): 增加一个dp时考虑的区间

---

Pipfile
Pipfile.lock
package.json
yarn.lock

更改：
1. GitHub 登录支持
2. 改进发送评论时的用户体验

chore: bump feedback-sys version to 0.3.1

---

docs/_static/js/oiwiki-feedback-sys-frontend.js
mkdocs.yml

该 PR 允许约 10% 的已登录 giscus 的用户访问 feedback-system，作为灰度测试的一部分。

feat: feedback-system gray test

---

docs/math/combinatorics/derangement.md

* fix: 将错位排列数的取整表达式由 仅向下取整 修正为 奇数向下取整偶数向上取整。

fix: 修正了“其他关系”板块中取整表达式的错误

---

docs/_static/js/oiwiki-feedback-sys-frontend.js
mkdocs.yml

fix: missing stringToHash function

---

docs/math/berlekamp-massey.md

根据下文代码实现不难发现他想表达的是 $F_{k-1}$ 而非 $F_{k}$

fix(berlekamp-massey.md): 修复公式错误

---

Pipfile
Pipfile.lock
package.json
scripts/post-build/inject-feedback-sys-frontend/task-handler.ts
scripts/update-feedback-sys-meta.py
yarn.lock

此 PR 更新 feedback-system 至 0.4.0，带来以下更新：
- 更好的前端表现
- 支持删除和编辑评论
除此之外，此 PR 更改了后端地址，以更好的描述服务名称。

chore: bump feedback sys 0.4.0

---

Pipfile
Pipfile.lock
mkdocs.yml
package.json
yarn.lock

此 PR 更新 OI Wiki Feedback System 至 0.5.0，新增以下功能：
- 账户登出
- 管理员功能
- 显示用户头像
- 超长评论折叠

chore: bump feedback-sys version to 0.5.0

---

docs/_static/js/oiwiki-feedback-sys-frontend.js
mkdocs.yml

feat: more friendly paragraph enable

---

docs/graph/graph-matching/graph-match.md

依 [格式手册](https://oi-wiki.org/intro/format/#latex-%E5%85%AC%E5%BC%8F%E7%9A%84%E6%A0%BC%E5%BC%8F%E8%A6%81%E6%B1%82) 之要求，将 $\emptyset$ 修改为 $\varnothing$

fix(graph/graph-matching/graph-match.md): eliminate `emptyset`

---

Pipfile
Pipfile.lock
package.json
scripts/update-feedback-sys-meta.py
yarn.lock

版本亮点：
- 修复了 textarea 聚焦异常的问题
- 修复了在获取 oauth_token 时无法正确处理其他查询参数的问题
- 修复了折叠/展开按钮不在页面中心的问题
- 修复了当页面无任何评论时 patch offset 报错的问题

feat: feedback sys 0.5.1

---

docs/lang/value-category.md

fix(lang/value-category.md) : Fixed spelling errors of vector

---

docs/ds/code/seg/seg_5.hpp

使用修改后的版本的代码在codeforces上通过了测试。https://codeforces.com/contest/558/submission/279781444
改之前样例都过不了（）

fix(docs/ds/code/seg/seg_5.hpp): 修复了将区间值设为0时懒惰标记完全不生效的问题

---

docs/_static/js/oiwiki-feedback-sys-frontend.js

本周好像没有接受到多少反馈，于是希望能进一步扩大测试的规模，对所有 giscus 用户开放 feedback sys。

feat: enable feedback sys for all giscus users

---

docs/tools/testlib/general.md

feat(general.md): 增加新的部分分写法：quitp

---

docs/_static/css/extra.css

详见 https://github.com/OI-wiki/feedback-sys/issues/73

fix(extra.css): 修改样式以修复 feedback-sys 中的代码块 bug

---

mkdocs.yml

https://github.com/OI-wiki/OI-wiki/pull/5836#issue-2511553690

fix(mkdocs.yml): 修改extra.css版本

---

Pipfile
Pipfile.lock
docs/_static/js/oiwiki-feedback-sys-frontend.js
package.json
yarn.lock

feat: update feedback-sys to 0.5.2

---

Pipfile
Pipfile.lock
package.json
yarn.lock

hotfix https://github.com/OI-wiki/feedback-sys/issues/80

feat: bump feedback-sys to 0.5.3

---

Pipfile
Pipfile.lock
docs/_static/css/extra.css
docs/_static/js/oiwiki-feedback-sys-frontend.js
mkdocs.yml
package.json
yarn.lock

更新日志：
- 修复表格右边评论按钮显示不全的问题
- 新增通过点击用户名或头像跳转到用户 GitHub 主页
- 新增分享功能

feat: feedback-sys v0.5.4

---

Pipfile
Pipfile.lock
package.json
yarn.lock

更新日志：
- 修复了中文用户名显示乱码的问题
- 修复了分享按钮权限控制错误的问题
- 更新了评论操作按钮的样式

feat: feedback-sys v0.5.5

---

Pipfile
Pipfile.lock
package.json
yarn.lock

更新日志：
- 修复了一个导致已登录用户无法管理他们自己评论的错误

feat: feedback-sys v0.5.6

---

docs/math/number-theory/sqrt-decomposition.md

feat(math/number-theory/sqrt-decomposition.md): 增加数论分块的拓展 & 改动部分格式

---

.github/workflows/build-pdf.yml
.github/workflows/incrementally-build-pdf.yml

Revert: https://github.com/OI-wiki/OI-wiki/pull/5099/commits/4c64c7535e4b6d8e7e25e5165157fad418c155e2

fix(.github/workflow/[incrementally-]build-pdf): change mirror to original site

---

mkdocs.yml

fix(mkdocs.yml): fix yaml format

---

docs/graph/code/mst/mst_3.cpp
docs/graph/code/mst/mst_3.java
docs/graph/code/mst/mst_3.py

fix(graph/code/mst): fix typo

---

docs/math/number-theory/stern-brocot.md

fix(math/number-theory/stern-brocot.md): 例题代码加上代码框

---

.github/workflows/build.yml

仅当在 master 分支时才运行 Update OI-Wiki Feedback System Meta 任务

chore: only run on master

---

docs/math/linear-algebra/product.md

1. 将所有的向量全部使用 `\boldsymbol` 样式；
2. 对「内积」和「向量积」两章节，使用三级目录「定义」、「性质」、「应用」和四级目录「几何定义」、「代数定义」重新划分内容；
3. 对「内积」这一章节，删去作为四级目录的应用条目；
4. 新增「内积」「向量积」「混合积」的线性性质；
5. 使用语义更加明确的 $\det(\boldsymbol a, \boldsymbol b, \boldsymbol c)$ 表示混合积；
6. 区分「二重外积」所有数学公式的标量乘法和向量内积。

refactor(math/linear-algebra/product.md): 重构页面，修正符号使用，调整章节，新增部分性质

---

Pipfile
Pipfile.lock
package.json
scripts/pre-build/install-feedback-sys-frontend.ts
scripts/update-feedback-sys-meta.py
yarn.lock

修改 feedbacksys 后端到prod部署上，并升级了 feedback sys 到 v0.5.7。
更新日志：
修复了无法复制有评论的文段的问题
修复了展开评论时没有动画的问题
优化了按钮的hover区域
修复了当用户重新登录时，其头像和用户 profile 未被更新的问题
优化了管理菜单的操作逻辑：当悬浮到整个评论的时候即可显示管理菜单，而不是必须悬浮到 header 上
用户头像不再可以选中

feat: switch to feedback sys production endpoint

---

Pipfile
Pipfile.lock
package.json
yarn.lock

更新日志：
启用了自定义域名和o11y功能
在后端的 / 上添加了一个 welcome page
修复了焦点打架没修好的问题

chore: bump feedback sys to v0.5.8

---

.github/workflows/build.yml
.github/workflows/celebration.yml
.github/workflows/config_test.yml
.github/workflows/test.yml
scripts/netlify/install-python.sh

在 #5894 的初次 build 中发现 pipenv 的安装脚本损坏。查询对应文件 [commit history](https://github.com/pypa/pipenv/commits/main/get-pipenv.py) 后推测为今早的 PR [#6260](https://github.com/pypa/pipenv/pull/6260) 带来了意料外的 binary data 改动。修改为[文档推荐安装方式](https://pipenv.pypa.io/en/latest/installation.html#preferred-installation-of-pipenv)应能解决此问题。

fix(.github/workflow): 修改了安装 pipenv 的方式

---

Pipfile
Pipfile.lock
docs/_static/js/oiwiki-feedback-sys-frontend.js
package.json
yarn.lock

更新日志：
修复了pending状态没有被正确显示的问题
修复了启用feedback sys时，手机上的正文宽度异常的问题
给没有评论的页面添加了信息，并添加了 footer
**重要：** 给所有用户都启用了 feedback sys

chore: upgrade feedback sys to v0.5.9 and enable it for all users🎉

---

Pipfile
Pipfile.lock
package.json
yarn.lock

更新日志见：https://github.com/OI-wiki/feedback-sys/pull/129

chore: bump feedback sys to v0.5.10

---

docs/dp/tree.md

feat(dp/tree.md): 添加树形 DP 常见状态和转移思路

---

docs/math/coordinate.md

fix(docs/math/coordinate.md): typo

---

docs/math/number-theory/basic.md

fix(math/number-theory/basic.md): 修正公式渲染效果

---

docs/string/code/trie/trie_1.cpp
scripts/ub-check.py

ci: ignore warnings about scanf

---

Pipfile
Pipfile.lock
package.json
yarn.lock

更新记录：https://github.com/OI-wiki/feedback-sys/pull/140

feat: update feedback-sys to v0.5.12

---

docs/intro/format.md

feat: 代码格式要求

---

docs/graph/matrix-tree.md

fix(matrix-tree): typo

---

docs/graph/graph-random-walk.md

fix(graph-random-walk.md): change R to R^2 according to original problem

---

docs/math/number-theory/prime.md

fix(prime.md): UB

---

docs/math/number-theory/sqrt-decomposition.md

fix(math/number-theory/sqrt-decomposition.md): fix typo

---

docs/ds/binary-heap.md

本文样例代码中，同时出现 std::swap() 和 swap()，有些奇怪。
经过查询 commit 记录，发现在 Commit 99438e0 有人将 swap() 改为了 std::swap()，但是没有改全，再结合排序等其他页面中出现交换变量时也采用 std::swap() 的形式，故将本页面的代码风格统一。

fix(ds/binary-heap.md): unify code style

---

docs/graph/shortest-path.md

1. 在 Floyd 应用处添加指向“最小环”板块的链接；
2. 修复 SPFA 代码中的 BUG：`vis`数组未更新，更换起点重复调用会导致最短路径错误。

fix(/graph/shortest-path/): 修复代码错误，添加链接

---

docs/math/algebra/group-theory.md

fix(group-theory.md): use darker color

---

scripts/post-build/minify-html/minify-html.sh

chore(minify-html.sh): minify-html: use GitHub release

---

docs/contest/oi.md

fix(oi.md): 调整了关于澳大利亚信息学奥林匹克竞赛的描述

---

docs/string/hash.md

fix(hash.md): formula

---

docs/lang/pb-ds/tree.md

fix(docs/lang/pb-ds/tree.md): 修复对于 erase 返回值错误的说明，添加了些补充说明 (#6006)

---

.github/workflows/build.yml

chore(workflow/build.yml): upgrade actions-gh-pages to v4

---

docs/graph/graph-matching/general-match.md

This commit changes a wrong title level. 构造完美匹配 should be a subsection of the second algorithm.

fix(graph/graph-matching/general-match.md): change wrong title level

---

docs/math/poly/fft.md

fixed when `on` equals -1, `y[i].y` is not divided by `len`

fix(math/poly/fft): fft template

---

docs/ds/fenwick.md

fix(fenwick.md): typo

---

.github/workflows/test.yml

fix https://github.com/OI-wiki/OI-wiki/actions/runs/12099118063/job/33736349748#step:4:225
tested in https://github.com/OI-wiki/OI-wiki/actions/runs/12103202348?pr=6030

ci(ub-check): set environ `PYTHONIOENCODING`

---

docs/lang/csl/algorithm.md

fix(lang/csl/algorithm.md): typo

---

docs/graph/hld.md

feat(graph/hld.md): 增加了树链剖分的题目

---

docs/math/number-theory/prime.md

主要内容：
- 提高标题等级，移除五级标题
- 将部分内容放入 details 语法框
- 移除部分不严肃的句子，修正部分用词
素性测试原文的写法不包括试除法，本次 PR 按照维基百科将试除法也算做素性测试。

perf(prime.md): 提高标题等级，增加文章可读性

---

docs/misc/mo-algo.md

source:#841
ADD: 不太清楚这么做有没有意义？

fix(misc/mo-algo.md): 将压行代码添加clang-format off

---

.github/workflows/build-pdf-typst.yml

根据 export 最近的更新， 同步更新了此处的 ci 脚本

chore: update typst workflow

---

docs/string/ac-automaton.md

feat(string/ac-automaton): 新增算法全名

---

docs/string/ac-automaton.md

fix(ac-automaton.md): typo

---

docs/lang/python.md

fix(python.md): format

---

.github/workflows/build-pdf-typst.yml

chore(workflow/typst): follow-ups for typst update commit

---

docs/math/bignum.md

fix: 移除示例代码内的无用数组

---

docs/ds/treap.md

fix(treap.md): 修正树高证明里面推导的笔误

---

docs/misc/two-pointer.md

fix(docs/misc/two-pointer.md): 数据范围

---

docs/graph/dfs.md

https://oi-wiki.org/graph/dfs/#comment-102

fix(dfs): fix python implementation 

---

docs/ds/splay.md

fix(splay.md): 更正 Splay 树中的复杂度证明

---

docs/ds/splay.md

fix(ds/splay.md): 修正 rk 函数实现

---

.github/workflows/build.yml
.github/workflows/check-characters.yml
.github/workflows/test.yml

chore(deps): upgrade tj-actions/changed-files to v46

---

.github/workflows/build-pdf.yml
.github/workflows/incrementally-build-pdf.yml

chore(latex): use the latest docker image

---

docs/contest/resources.md

feat(contest/resources.md): 添加 QOJ 并维护 CDOJ 状态

---

docs/contest/resources.md

fix(contest/resources.md): fix unreachable link and do cleanups

---

docs/ds/fenwick.md

fix(ds/fenwick.md): correct variable initialization syntax

---

.github/workflows/build-pdf-typst.yml
.github/workflows/test.yml

Fix #6181 Suggested by @Enter-tainer

fix(workflows): update package lists from apt repositories first

---

docs/math/linear-algebra/vector.md

fix(math/linear-algebra/vector): 修正空间向量基本定理章节 向量数量问题

---

docs/contest/common-mistakes.md

HuangYiming0608 是我之前的 Github 账号，现在已经注销（你可以搜索一下），这是我的新账号，望修改我的用户名。我对管理员因我个人问题而需要处理 PR 深感抱歉。

fix(contest/common-mistakes.md): 更改用户名

---

docs/math/combinatorics/inclusion-exclusion-principle.md

fix(inclusion-exclusion-principle.md): typo

---

docs/graph/matrix-tree.md

fix(matrix-tree.md): 修正了两处笔误

---

docs/math/poly/ntt.md

fix(docs/math/poly/ntt.md): typo in scanf usage

---

.github/workflows/build-pdf-typst.yml

chore(workflow/typst): upgrade typst-community/setup-typst to v4

---

docs/math/numerical/gauss.md

高斯消元法解异或方程组中的异或方程组一处b_1应修正为b_m

fix(gauss.md): 修正一处方程

---

docs/basic/code/insertion-sort/insertion-sort_1.java
docs/basic/insertion-sort.md

新增插入排序代码实现部分，插入排序的java实现
更新insertion-sort.md中插入排序代码实现部分，新增java代码实现部分

fix(basic/insertion-sort): 添加插入排序的java代码实现

---

docs/math/algebra/group-theory.md

fix(math/group-theory.md): 修正两处typo

---

.github/workflows/build-pdf-typst.yml
.github/workflows/build-pdf.yml
.github/workflows/incrementally-build-pdf.yml

update workflows due to changes in https://github.com/OI-wiki/OI-Wiki-export/pull/97.

chore(workflows): update export build commands

---

docs/math/algebra/basic.md

see https://github.com/OI-wiki/gitment/discussions/1253#discussioncomment-13107490

fix(algebra/basic.md): typo

---

.github/workflows/build.yml
scripts/update-feedback-sys-meta.py

见 #6244 
由于 all_old_new_renamed_files 会无视 CI 的 filter，因此在脚本中添加了一个 filter 以获取正确的结果。

fix: rename changed files

---

docs/graph/connectivity.md

fix(docs/graph/connectivity.md): typo

---

docs/math/order-theory.md

see https://oi-wiki.org/math/order-theory/#comment-297

fix(order-theory): typo

---

docs/lang/array.md

fix(lang/array.md): 标明越界访问是 UB

---

docs/graph/cut.md

似乎是 https://github.com/OI-wiki/OI-wiki/commit/149c97ab6f8498af1310938ce65750a5307a2e22#diff-23aa45fe274d9acd426ed990485e1c6e6381de68357e6b38ab879108005f1742R1 意外引入的。

fix(cut.md): 删去多余的逗号

---

docs/ds/code/sparse-table/sparse-table.py
docs/ds/sparse-table.md

feat(ds/sparse-table.md): 添加 Sparse Table 的 Python 模板

---

docs/graph/images/bi-graph-2.svg
docs/graph/images/bi-graph-2.tex

正文写的是 DFS 生成树，配的图的非树边不是 back edge，不大好，更换一下图片。

fix(bi-graph.md): correct pic

---

docs/math/number-theory/prime.md

see https://oi-wiki.org/math/number-theory/prime/#comment-379

fix(prime.md): typo

---

scripts/post-build/minify-html/minify-html.sh

chore(minify-html.sh): upgrade minify-html

---

scripts/post-build/math/task-handler.ts

chore(task-handler.ts): force cache-busting

---

docs/geometry/3d.md

fix(geometry/3d.md): 修改线面角定义错误 (#6350)

---

Pipfile
Pipfile.lock
package.json
yarn.lock

fix https://github.com/OI-wiki/feedback-sys/issues/145

chore: bump feedback sys to 0.5.13

---

docs/tools/special-judge.md

feat(tools/special-judge.md): add HDOJ

---

scripts/post-build/math/task-handler.ts

chore: use sha256 instead v=\d to invalidate mathjax.css cache

---

docs/string/hash.md

fix(string/hash.md): typo

---

docs/contest/oi.md

fix(contest/oi.md): 修改NOI保送,进入国家集训队所需排名为50

---

docs/math/number-theory/min-25.md

fix(math/number-theory/min-25.md): 修复了“解释”一栏中的疑似错误公式

---

.github/workflows/check-format.yml
docs/ds/code/seg/seg_5.hpp

feat: `.h`, `.hpp`, `.c` support by clang-format

---

docs/dp/knapsack.md

feat(knapsack.md): new example

---

docs/graph/graph-matching/graph-match.md

feat(graph/graph-matching/graph-match.md): 修改括号简写以包含`的`

---

docs/math/number-theory/bezouts.md

see https://github.com/OI-wiki/gitment/discussions/1272#discussioncomment-14161744

fix(bezouts.md): typo

---

docs/graph/block-forest.md

feat(graph/block-forest): 增加习题

---

docs/math/number-theory/prime.md

feat(prime.md): add correctness proof for randomized Miller–Rabin test

---

docs/math/number-theory/continued-fraction.md

see https://oi-wiki.org/math/number-theory/continued-fraction/#comment-481

fix(continued-fraction.md): typo

---

docs/math/number-theory/quad-residue.md

调整了含有脚注标号的句子，和 Tonelli–Shanks 算法部分的语句。
PS：严格来说，$Z_p^*$ 里 $n$ 次单位根一定是 $n$ 阶元素的幂这一点，并不是那么直接的。但是苦于没有单位根的内容（#6476），暂且先不动这里。不然又要引抽象代数的东西。

perf(quad-residue.md): improve readability

---

docs/ds/seg.md

feat(seg.md): 增加动态开点线段树的习题

---

docs/math/code/inverse/inverse-3.cpp
docs/math/code/inverse/inverse-3.py

perf(inverse-3.*): add comments

---

docs/math/combinatorics/fibonacci.md

fix(math/combinatorics/fibonacci.md): fix unreachable link

---

docs/contest/problemsetting.md

洛谷申请公开赛的方式已经更改为工单修改，该 PR 对此进行修改。

fix(contest/problemsetting.md): 修改洛谷比赛申请流程

---

docs/ds/rbtree.md
docs/graph/flow/max-flow.md

fix(*): fix definition-case warning

---

docs/edit-landing.md

style(edit-landing.md): remove unnecessary lint skip mark

---

docs/misc/hoverline.md

fix(misc/hoverline.md): fix-a-mistake

---

docs/lang/pas-cpp.md

Address: https://github.com/OI-wiki/OI-wiki/pull/6578#discussion_r2376642276 and https://github.com/OI-wiki/OI-wiki/pull/6578#discussion_r2376660184

fix(lang/pas-cpp.md): address some comments

---

docs/dp/opt/wqs-binary-search.md
docs/lang/new.md

fix(lang/new.md, dp/opt/wqs-binary-search.md): broken links with parenthesis

---

docs/math/numerical/interp.md

close #6587
另外 Newton forward divided difference formula 这一名词在 https://en.wikipedia.org/wiki/Newton_polynomial 里没有 citation，所以删除了。

fix(interp.md): minor

---

docs/math/number-theory/primitive-root.md

补充一些关于求原根复杂度的分析。
另外，调整了一个记号。数论中的 $\Omega$ 记号和计算复杂度理论中的 $\Omega$ 记号含义 [并不相同](https://en.wikipedia.org/wiki/Big_O_notation#Big_Omega_notation)：
- 数论中指两者之商的上确界为正数；
- 计算理论中指两者之商的下确界为正数。
虽然这一页面是数论相关页面，但是为了避免和其他页面相混淆，做相应更正。

feat(primitive-root.md): 补充求原根算法及复杂度分析

---

docs/graph/prufer.md

在例题部分添加了 Luogu P6086（模板题）和 Luogu P11039（图连通方案数公式的应用）。

feat(graph/prufer.md): 添加例题
