OI-wiki/OI-wiki

static/disqus.html
发现这个参数其实是可选的，那就用默认的吧：location.href
=> fix: fix gitment

docs/introduction/resources.md
The cplusplus.com is outdated. There's nothing about C++14/17/20.
The cppreference.com updates timely following drafting, and supports Chinese. It looks delicious.
=> use cppreference.com instead of cplusplus.com

.github/pull_request_template.md
phi 和 varphi 在不同字体中显示得很混乱。应该统一按照 LaTeX 中规定写法 `$\varphi$` 为 ![](https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Greek_phi_Didot.svg/11px-Greek_phi_Didot.svg.png) ，`$\phi$` 为 ![](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Greek_phi_Porson.svg/10px-Greek_phi_Porson.svg.png)。
> Wikipedia 上的说法：
> 
> In LaTeX, the math symbols are \Phi (![](https://wikimedia.org/api/rest_v1/media/math/render/svg/21242b7aa20bff076c14a47d1a2d9f0afb35f165)), \phi (![](https://wikimedia.org/api/rest_v1/media/math/render/svg/30ae608cf0ade0577802bc4ffa026a29ab35c365)), and \varphi (![](https://wikimedia.org/api/rest_v1/media/math/render/svg/ca38cae992cf33a25f380c941c0e3f34193704ad)). 
（虽然 Wikipedia 上说 ![](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Greek_phi_Porson.svg/10px-Greek …
=> phi 和 varphi 的正确写法

netlify_build.sh
netlify 限制内存占用为 2G，现在用的这个 mathjax-node-page 占用内存太大，作者表示懒得改，最好等 mathjax-v3 出来。ref: https://github.com/pkra/mathjax-node-page/issues/72
解决办法或许可以考虑换用 wikipedia 渲染 mathjax 的方案，不过最近优先级并不高还没有仔细研究过
=> remove render_math.js in netlify

.travis.yml, gulpfile.js, package-lock.json, package.json, scripts/netlify_build.sh
使用了 `htmlmin` 来压缩 `html`，用 `imagemin` 来压缩 `svg`, `png`, `svg`, `gif`，用 `purifycss` 和 `cssnano` 来压缩 `css`
压缩前，`site/` 的大小是 25.4 MB ，压缩后为 20.8 MB
=> feat: add minify scripts to make the site smaller

docs/intro/testlib/checker.md, docs/intro/testlib/general.md
修复了 testlib 相关页面的几处错误，有些地方作了小改。关于 `InStream::ensuref()` 的说法，用当前版本的 testlib.h 做过实验，希望没有问题叭
改动比较杂，辛苦 reviewer 啦
----
=> 修复 testlib 相关的几处小错误并略作改进

docs/misc/matrix-tree.md
=> fix: matrix-tree.md修锅

docs/ds/odt.md
=> fix: 珂朵莉树词条代码中的一个bug

README.md
=> 修复Readme.md里面Travis CI的build状态

docs/lang/csl/associative-container.md
insert的返回值对于Oier们来讲具有很好的便利性，在BZOJ 2203A New Operating System一题中有很好的体现，或许有其他的写法，但是直接使用insert的返回值会更加的高效，使代码更简洁，有加入的必要
1. 注意有没有 typo
=> 关于关联式容器中set和map的insert的返回值

docs/geometry/2d.md
多边形面积<del>距离</del>应该是向量叉乘和的模而不是向量叉乘模的和。
=> 修复了平面计算几何的一个错误

docs/graph/bfs.md
考虑到 BFS 的顺序，若某个顶点 `(x,y,dir)` 已被访问过，则 `dist[x][y][dir]` 已被松弛，此时条件 `d < dist[x][y][dir]` 必为假。故移除数组 `vis`。
1. 注意有没有 typo
=> 【0-1 BFS】移除不必要的逻辑

.travis.yml
1. 注意有没有 typo
-----
Add `.nojekyll` file during Travis CI build, stop GitHub Pages from ignoring files with underscores prefixed.
Ref:
- https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/
- https://help.github.com/en/github/working-with-github-pages/about-github-pages#static-site-generators
This PR also helps https://github.com/OI-wiki/gitment/issues/19#issuecomment-642368053
=> chore(gh-pages): stop ignoring files with underscores prefixed

.travis.yml, scripts/replace_cdn.js
1. 注意有没有 typo
----
This is an emergency fix for #2290, blame @sukkaw.
- Now cdn replacement will begin right before the deployment toward `gh-pages`
- A new directory `site-cdn-pages` will be created during the replacement
- After `site` is deployed to `gh-pages`, `site-cdn-pages` will be deployed to `cdn-pages` branch as expected.
=> refactor(cdn): replace cdn before deploy

README.md, docs/string/bm.md, scripts/build.sh, scripts/install_theme.sh, scripts/netlify_build.sh
如题，
1. 目前，在他们解决这个bug之前，[markdown](https://github.com/Python-Markdown/markdown)渲染块Latex时候遇到其中的空行会将整个结构分成毫无意义的上下两部分，使得HTML上的Latex块无法被识别，从而无法被MathJax渲染。
2. 改正了REAME上关于本地运行的说明
=> 更正README关于本地运行的说明以及解决./docs/string/bm.md块LaTex 不能正常的显示的问题

docs/intro/wsl.md
将WSL文章【参考资料】中的第一项——洛谷日报#6的链接进行更改。原来链接指向洛谷日报索引，修改后直接指向原文，使查看参考资料更为方便。
=> Change one of the reference links.

docs/string/trie.md
> @Falicitas
> 题目fusion tree的第87 & 89行的if判定那写错了，应改为if(fa[fa[x]]!=-1)云云，由于rt周围的点若被修改会RE（虽然数据能过）
这位同学发现了一处错误，数据能过，但实际上是不对的。
这个代码是我写的，没有注意这个地方，现已改正。
对我的疏忽而抱歉，同时感谢这个同学的阅读。
1. 注意有没有 typo
=> 修改例题 fusion tree 代码一处错误

docs/basic/radix-sort.md
Thanks for reviewing this.
The original code will generate an **INCORRECT** output on the following testcase:
```c++
int main()
{
k = 2;
w[1] = w[2] = 2;
n = 3;
a[1].key[1] = 2, a[1].key[2] = 1;
a[2].key[1] = 1, a[2].key[2] = 1;
a[3].key[1] = 1, a[3].key[2] = 2;
radix_sort();
cout << a[1].key[1] << a[1].key[2] << endl;
cout << a[2].key[1] << a[2].key[2] << endl;
cout << a[3].key[1] << a[3].key[2] << endl;
/*
Incorrect Output:
12
11
21
*/
return 0;
}
```
Ouput is now **CORRECT** after fixing the bug.
```c++
int main()
{
k = 2;
w[1] = w[2] = 2;
n = 3;
a[1].key[1] = 2, a[1].key[2] = 1;
a[2].key[1] = 1, a[2].key[2] = 1;
a[3].key[1] = 1, a[3].key[2] = 2;
radix_sort();
cout << a[1].key[1] << a[1].key[2] << endl;
cout << a[2].key[1] << a[2].key[2] << endl;
cout << a[3].key[1] << a[3].key[2] << …
```
=> Fixed a bug in the C++ example of radix sort

mkdocs.yml, requirements.txt
~~错位问题是因为代码被 \<pre\> 和 \<code\> 套了两层，一层一个 padding，我试试能不能修~~
已解决，错误原因：
> https://python-markdown.github.io/extensions/code_hilite/
>
> Additionally, if using Pygments >= 2.4, the output will be wrapped in `<code>` tags, whereas earlier versions will not.
---
1. 注意有没有 typo
=> 修复代码块行号（fix #2114 & #2160）

docs/math/primitive-root.md
个人的理解是\gcd(t,\varphi(p))整除{\frac{\varphi(p)}{d_{i}}}，这里应该是和a没关系的。
1. 注意有没有 typo
=> 修改了“求一个原根”的证明的错误

scripts/install_theme.sh
与内容无关
macOS sed -i 需要带一个字符串作为备份源文件的文件名称 否则会出错
=> 修改部署脚本在mac上出错的问题

docs/dp/basic.md
如该解法中代码上面的算法描述，在dp中找到第一个大于a[i]的元素，则应该使用upper_bound，而不是lower_bound。
1. 注意有没有 typo
=> 修正最长不下降子序列nlogn解法中的代码错误

docs/math/prime.md
fix(typo): fix a typo in a formula in math/prime
It obviously should be `\equiv` not `=`.
=> fix(typo): fix a typo in a formula in math/prime

docs/ds/sparse-table.md
Fix runtime error in example code.
定义数组大小为`logn`, 但是在 [第83行](https://github.com/OI-wiki/OI-wiki/pull/2751/files#diff-3c3a736232b812155587f9c4d5792e4475f4942aed73e0f0dbf99a56c71cdc02L83) 访问了下标为`logn`的地方.
修复数组大小为`logn+1`.
1. 注意有没有 typo
=> fix:(sparse-table.md) Fix runtime error in example code

docs/dp/opt/quadrangle.md
u+1 \leq v+1 \leq r_1 \leq v_2
改为
u+1 \leq v+1 \leq r_1 \leq r_2
=> 发现四边形不等式优化中的2D1D的引理1证明过程中出现内容错误并进行了修改

docs/string/bm.md
本PR主要是为了修复一个算法代码上的bug，顺带改了几个之前就想改，但总感觉改不胜改的目前阶段所能发现的几处小笔误；
另外增加了一点点使内容更易于被理解的增改。
=> [fix][BoyerMoore] fix a code bug, a little typo && refine text...maybe

docs/dp/knapsack.md
可能是洛谷更新题目和数据了，原来的代码有两个地方不对，一是数组的大小不对，二是 f 数组应该开 `long long`。
1. 注意有没有 typo
=> 修改完全背包的例题代码

docs/contest/icpc.md
icpc 官网已经移至 <https://icpc.global>，此处进行修改。
=> 更新 ICPC 官网

docs/tools/judgers.md
1.  we can pass parameter into `./make` instead of using `sed` to modify the file,
`-jn` can be passed although `-j n` can't.
2.  we can install the executable file into PATH instead of throwing it into home dir.
the result of git blame: https://github.com/OI-wiki/OI-wiki/commit/47acc594f2d94423d319a7b1ee83546ad29552a6
=> fix(tool/judgers.md): wrong usage in building lemon

docs/intro/format.md
虽然我们已在格式手册中提示使用稳定的引用链接，但是仍然不能避免链接失效的情况。
在这方面，维基百科的做法给我们一个提示，我们可以在添加引用链接的同时，将其保存备份与[互联网档案馆的时光机](https://web.archive.org/)。
维基百科上常见的“存档于”：
而更遥远的想法，则是准备一个 Bot/CI，自动地将 OI Wiki 中的引用链接定时地保存于互联网档案馆，并且定期更新。
更进一步还可以，当链接失效的时候自动用互联网档案馆的链接替换失效链接。
这只是一个小小的想法，希望与大家一同讨论。
=> feat(intro/format.md): 添加将引用链接存于互联网档案馆的提示

docs/tools/editor/guide.md
说实话这个 Workaround 我是不太想加的，但是我在测试的时候确实遇到了反复的
玄学错误，典型例子是这样的：
```log
mkdir: cannot create directory ‘/usr/share/doc/GUIDE’: No such file or directory
```
分开创建目录可以解决这个问题，就好像 `-p` 参数被忽略了一样…………
为了防止不必要的麻烦，我觉得还是加上为好
=> fix(tools/editor/GUIDE): a workaround for some error in checkinstall

docs/misc/parallel-binsearch.md
对于小于等于二分的mid的答案，应该划到左边，而不是将mid小于等于的答案划到左边
=> fix parallel-binsearch.md

docs/math/crt.md
“r_{ij} = (p_i)^{-1}”用在此处不恰当（因为上下文中涉及了不知道数量的模数），将其改成了逆元定义中的式子；修改了下标的格式（把类似 a_{ij} 的改成了 a_{i,j}）；在几处添加了乘号，可能能降低看错的概率。
=> <fix>(crt.md): 修正了几处不够恰当的地方

.github/workflows/build-pdf.yml
构建PDF时只clone最近的一个版本 加快构建速度 节约资源
=> feat: fast CI git clone

docs/contest/resources.md, docs/ds/dividing.md
Years ago in merged pull request #1223, I added NOJ, so I added myself as one of the page authors.
The main reason for this pull request however is the starting date of NOJ is wrong, it should be 2008. I took the responsibility of rebuilding NOJ from 2018 to date, but as a service, NOJ has been running for decades.
[Web Archive](https://web.archive.org/web/20130414064307/http://acm.njupt.edu.cn/welcome.do;jsessionid=C003E67855DD01EE85A843C75CD94726?method=index)
=> add author and update NOJ start date

docs/ds/bst.md
> `insert` 函数里面没有设置 `lc[o]` 和 `rc[o]` 的值, 那后面的操作根本进行不了啊
_Originally posted by @huaruoji in https://github.com/OI-wiki/gitment/issues/335#issuecomment-820830898_
=> Fix(BST): Fix insert()

docs/ds/lct.md
原先的写法中判断是否有左儿子在 pushDown 前，可能会出问题。
实际上绝大多数题目中都可以证明这里不需要 pushDown，所以原先代码能在不少题目上 AC。但是对于魔改的 LCT 这里可能会导致错误。
=> fix(lct.md): fix `Find()`

docs/lang/csl/container-adapter.md
针对 https://github.com/OI-wiki/OI-wiki/pull/3127#issuecomment-826809173 进行补充。
C++14后lambda参数支持类型推导的特性在语言部分已经写有，此处不再补充。此处不假设代码在C++14标下编译，因此把类型补全。
1. 注意有没有 typo
=> 明确lambda类型

docs/math/mobius.md
数论莫比乌斯反演(倍数形式)的证明中,最后一步交换求和顺序时,下标出现了错误.
此commit对该处错误进行了修正.
这个错误并非由我发现,我最早在[link](https://github.com/OI-wiki/gitment/issues/56#issuecomment-836229635)看到了这个问题.  
感谢@sosupro
----------------------
1. 注意有没有 typo
=> fix(mobius.md): 修订了对于倍数形式的证明中的下标范围.

docs/_redirects
dead link in issue #1884
old link archive at https://web.archive.org/web/20200513055304/https://oi-wiki.org/lang/editor/npp/
=> fix: missing redirect for /lang/editor

docs/math/primitive-root.md
close #3195 
性质3的充分性证明的第二行的末尾，应该是 $a^{\delta_m(ab)\delta_m(b)}$.
类似的证明可以看https://www.cnblogs.com/ldysy2012/p/12208905.html 性质9
原根个数证明的第四行，是 $1\leq k \leq \varphi(m)$
这个就是$1\leq k \leq \varphi(m)$中有$\varphi(\varphi(m))$个原根，由欧拉函数定义可证
=> fix mistakes in #3195 to update primitive-root.md

docs/ds/splay.md
虽然实际使用中常常先 ins 一个 inf 和一个 -inf，但是这里没有说明，那么是有可能出现不存在前驱/后继的情况的。此时如果无脑 Splay，在 Splay 函数中又是无脑设置根节点的话，会出现把 0 节点作为根节点，继而让整棵树子节点关系出错的情况。
1. 注意有没有 typo
=> 修复了 pre 与 nxt 函数中没有检查是否存在前驱后继的问题

docs/math/quick-pow.md
Reverts OI-wiki/OI-wiki#3294
考虑到 mod 1 的情况没有现实意义，实践中几乎不会出现这种情况，因此撤回原 PR 的修改。
=> Revert "fix(math/quick-pow): initialize res to 1%mod in case exp=0 and mod=1"

docs/basic/greedy.md
修改了 贪心(greedy)页面 [NOIP 2012 国王游戏] 解题思路 里的 4 个公式 typo
第 $i + 1$ 个大臣得到的奖赏就是 $\dfrac{s \cdot a_{i+1}} {b_{i+1}}$
这里有误，应改为
第 $i + 1$ 个大臣得到的奖赏就是 $\dfrac{s \cdot a_i} {b_{i+1}}$
后面的相关推导也一并修改了
1. 注意有没有 typo
=> 修改了 贪心(greedy)页面 [NOIP 2012 国王游戏] 解题思路 里的 4 个公式 typo

docs/basic/selection-sort.md
Not just delete to make sure the struct of statements are aligned
across `*-sort.md`.
=> fix: stmt redundancy with aligned pg struct kept

docs/math/number-theory/primitive-root.md
对该命题进行了修改，证明沿用了原有的证明方法，只是把p都改成了m
1. 注意有没有 typo
=> 原根判定定理的命题和证明有较大出入

docs/math/quick-pow.md
修复了快速幂中快速乘的代码实现部分的一个细节
前文提到运用 unsigned long long 的自然溢出，但此处类型转换却转换为了 unsigned 类型，
在C++中，unsigned 是 32 位的，所以将此处的 unsigned 改为 64 位的 unsigned long long
如果不进行这样的更改的话，有 hack 数据 如：
```cpp
binmul(20436672733ll,20436672733ll,21993833369ll)
```
如果不进行这样的更改的话，函数返回值是 8916298685417424728 ，更改后得到正确值 3500622783
------
1. 注意有没有 typo
=> fix(math/quick-pow.md): 快速乘的代码实现中unsigned应改为unsigned long long类型

docs/basic/merge-sort.md
链接实际上指向维基百科的「归并排序」词条，本文章主题也是「归并排序」。
=> fix: 纠正 merge-sort 页面「归并排序」维基百科词条链接标题

docs/math/number-theory/euler.md
euler.md 中一会是 $n$，一会是 $s$，上下文应统一。
=> fix(euler.md): 修正变量名不规范的问题

docs/intro/format.md
=> fix: 格式手册中关于折叠框标题语法的补充

docs/contest/resources.md
此域名至少从20210414180310起就被赌博网站占据了，没有复原迹象，也没有搜到新域名。
参见：https://web.archive.org/web/20210414180310/https://www.algomation.com/
1. 注意有没有 typo
=> fix(resources): remove `www.algomation.com`

docs/dp/opt/monotonous-queue-stack.md
=> fix(单调队列优化动态规划推导公式错误):修复了单调栈页面的一个公式错误

docs/lang/c-cpp.md
C supports out-of-order designated initialization, nested designated initialization, mixing of designated initializers and regular initializers, and designated initialization of arrays, but C++ doesn't support
MSVC doesn't implement this optional feature, and doesn't support some C11 optional features. 
It doesn't implement C99 as well.
[1]: https://en.cppreference.com/w/cpp/language/aggregate_initialization
[2]: https://en.cppreference.com/w/c/language/struct_initialization
=> fix(lang/c-cpp): C supports some designated initializers features but C++ doesn't

docs/math/poly/lagrange.md
拉格朗日插值法中第一种推导过程中，关于 `f(x)` 的多项式线性同余方程组的第二个方程的角标错误，应当将 `f(x) ≡ y_n (mod f(x - x_2))` 改为 `f(x) ≡ y_2 (mod f(x - x_2)) `
1. 注意有没有 typo
=> 修复拉格朗日插值法第一种推导过程中线性同余方程组中的一处角标错误

docs/math/number-theory/gcd.md
对于扩展欧几里得求出的可行解，必有 $|x|\le b,|y|\le a$。
=> feat(gcd): 添加扩展欧几里得的值域分析

docs/string/kmp.md
前缀函数朴素算法的 python 代码在数组 slicing 时有错误。
1. 注意有没有 typo
=> fix(string/kmp): erroneous python code snippet

docs/_static/css/extra.css
=> fix: tweak size and vertical align of icons in page copyright

.github/workflows/pr-stale.yml
Upstream default settings is garbage, it enable for all by default.
=> fix(ci/pr-stale): disable for issues

gulpfile.js
=> fix(build): disable `removeOptionalTags` in html-minifier

docs/geometry/nearest-points.md
修改了归并排序中 STL 的应用，将 std::merge() 变为 std::inplace_merge()，删掉 std::copy()，降低时间复杂度。
=> fix(geometry/nearest-points): 修改了归并排序中 STL 的应用

scripts/BaiduPusher.sh
I tried to fix it by removing this line,
It shouldn't do anything extra in a normal shell script.
But I'm not sure if this is necessary for the job.
cc @abc1763613206
=> fix(script/BaiduPusher): try to fix by remove useless `source /etc/profile`

docs/math/number-theory/crt.md
中国剩余定理保证了在 n（方程组中所有模数的乘积）中有唯一解，这里其实并不需要一个额外的模数 mod，而是应该对 n 取模。
=> fix(math/number-theory/crt): 修正中国剩余定理代码中的模数

docs/math/gauss.md
RT，应当是度数矩阵减邻接矩阵，下面行列式结果是对的但是正负号也都反了
1. 注意有没有 typo
=> 高斯消元里矩阵树定理的度数矩阵与邻接矩阵的加减顺序写反了

docs/dp/opt/slope.md
根据[原题](https://loj.ac/p/10188)题面所述，$L$ 是一个常量，这里的简化题意中，求和符号用大写字母 $L,R$ 来对应区间显然不合适。
数据范围的部分就纯粹是抄写错误了，我按照原题修改好了。
顺手在后面推导的第一步加了一个更详细的中间步骤。
1. 注意有没有 typo
=> fix(slope.md): 修正了题面的一个错误

scripts/post-build/math/task-handler.ts
后端渲染 mathjax 之后前端就不需要这些文件了，删掉可以让部署更轻一点
=> feat(scripts/post-build/math): remove unused client-side rendering scripts

mkdocs.yml
在 #4044 中，C++ 其他语言对比的内容被增加到了 `C 与 C++ 区别` 页面中，而且 md 文件名也从 `c-cpp` 改为 `cpp-other-langs`，但是对应的文章标题并未改变，所以提出本 PR 进行更改
1. 注意有没有 typo
=> fix(mkdocs.yml): Change title of cpp-other-langs to "C++ 与其他常用语言的区别"

.github/workflows/build-pdf.yml
when members contribute, the latex action checks twice.
=> ci: only add checks when pushing to master

.github/workflows/build-pdf.yml
=> fix(workflows/build-pdf.yml): lock latex by repo

.bashrc, Dockerfile, docs/intro/docker-deploy.md
fix #2181 中的容器外拒绝访问的问题。
通过修改mkdocs.yml配置文件，使 MkDocs 监听0.0.0.0，即包括但不限于本机的访问。
处于安全原因，我注释掉了这一行，并在 README “部署”章节中添加了打开方法。
Docker容器一般都需要取消这个注释，以在容器外正常访问，但容器内默认没有装 Vi 等文本编辑器。我在mkdocs.yml配置文件所在目录中创建了另一个修改好的文件，并修改Dockerfile，在构建容器时拷贝覆盖过去。
=> fix(intro/docker-deploy, .bashrc, Dockerfile): 解决本地部署服务器时无法使用其他设备访问的问题

docs/ds/ett.md, docs/ds/treap.md
原文中非旋 Treap 完整代码中的 qnex 函数 漏加了 int ret = qval_by_rank(temp.second, 1); 一句，会导致CE，进行了修改。
对于非旋 Treap 中 split_by_rk 的返回值，写成 tuple 的形式并用 tie 接受返回值显然更加直观且便捷。
=> 对原文中非旋 Treap 的完整代码中的错误进行修改并对 split_by_rk 函数进行重写

docs/graph/steiner-tree.md
=> fix(steiner-tree): 删除多余空格

docs/ds/hash.md
使用 (u % SZ + SZ) % SZ 而非 u % SZ 的原因是 C++ 中的 % 运算无法将负数转为正数。
=> fix(ds/hash): 更新代码实现中取模运算

docs/math/number-theory/discrete-logarithm.md
修复一个前后式的顺序错误
描述 BSGS 为什么要求 a⊥p 的时候前后式的关系混乱，应该为“后式是由前式除以 a^B 得到的”。
- [√] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。
=> fix(math/number-theory/discrete-logarithm.md) 修复一个前后式的顺序关系错误

docs/graph/lca.md
将代码修改为了和文字描述对应的实现
rvalue | SIGHIBR, [2022/11/6 23:39]
式子没错
rvalue | SIGHIBR, [2022/11/6 23:39]
然后和代码并不对应
rvalue | SIGHIBR, [2022/11/6 23:40]
代码是另一种写法
rvalue | SIGHIBR, [2022/11/6 23:41]
那看来就只是代码和式子脱节了(
=> fix(lca): 统一文字描述和代码实现

.github/workflows/test.yml, docs/dp/code/dynamic/dynamic_1.cpp, docs/dp/code/tree/tree_3.cpp, docs/ds/code/treap/treap_1.cpp, docs/math/code/quick-pow/quick-pow_1.cpp, docs/misc/code/cdq-divide/cdq-divide_2.cpp, docs/misc/code/cdq-divide/cdq-divide_3.cpp, scripts/test.py
----
- `.github/workflows/test.yml`：仅在 C++ 文件、`/scripts/test.py` 修改时执行测试，不进行不必要的 GitHub Actions 工作流。
- `docs/dp/code/dynamic/dynamic_1.cpp`、`docs/dp/code/tree/tree_3.cpp`、`docs/ds/code/treap/treap_1.cpp`、`docs/math/code/quick-pow/quick-pow_1.cpp`、`docs/misc/code/cdq-divide/cdq-divide_2.cpp`、`docs/misc/code/cdq-divide/cdq-divide_3.cpp`：解决 C++ 17 不兼容而编译错误的问题。
- `scripts/test.py`：设定编译参数为 `g++ -std=c++17 cppfile.cpp -o cppfile`，防止未来默认的 C++ 为更高版本而再次造成编译错误等问题。
> **Note**
> 尽管所有代码都可以正常编译、运行、通过评测，但没有解决 ISO C++ 17 中新产生的一些警告。
----
原拉取请求：#4486 
运行结果：https://github.com/yusancky/OI-wiki/actions/runs/3692314693 ／ https://github.com/OI-wiki/OI-wiki/actions/runs/3692408735/jobs/6251276110
=> fix: 解决部分代码因变量/数组名与 C++ 17 关键字冲突而导致编译错误的问题

docs/ds/skiplist.md
参考[此处](https://stackoverflow.com/questions/63575194/why-does-c-stdmin-cant-use-a-static-field-as-its-parameter-when-compile-on#comment112421595_63575194)，对 const static 成员使用 std::min 在 O0 优化下会导致链接错误。
=> fix(ds/skiplist.md): 修正参考代码

docs/lang/python.md
=> fix(python.md): 修正“类型标注”中示例代码未正确显示的错误

docs/math/simplex.md
没有考虑到不对变量做出限制的情况，例如，输入
```
7 4
3 1 2 0 0 0 0
1 1 3 1 0 0 30
2 2 5 0 1 0 24
4 1 2 0 0 1 36
```
就会死循环，具体可以参见 国家集训队2016论文集《浅谈线性规划与对偶问题》P38
=> fix(docs/math/simplex.md): 修改代码死循环

docs/math/number-theory/primitive-root.md
将原根定义中的错误语句 0<=i<p 改为正确语句 0<i<p。
=> fix primitive-root.md：修改原根定义的一处错误

docs/ds/code/persistent-seg/persistent-seg_1.cpp
修正了原来因为没有正确按秩合并而导致复杂度错误的代码。
原本的代码的 `tree` 数组储存的是线段树的节点，但在原本的代码的第 30 行和第 70 行等地方却误将其作为当前序列的内容使用。这一问题导致原本的代码提交到[洛谷上的对应模板题](https://www.luogu.com.cn/problem/P3402)后会出现 [TLE](https://www.luogu.com.cn/record/105014139)。之所以是 TLE，是因为没有正确按秩合并只影响复杂度，不影响逻辑上的正确性。同时因为原题数据强度不高，大部分测试点都能 AC。
新的代码修正了这一错误，并且在原题处提交时能够 [AC](https://www.luogu.com.cn/record/105078457)。
=> fix(ds/code/persistent-seg/persistent-seg_1.cpp): 修正了原来因为没有正确按秩合并而导致复杂度错误的代码

docs/math/number-theory/primitive-root.md
=> fix(math/number-theory/primitive-root.md): 修改了关于原根符号不规范的问题

docs/dp/basic.md
原本对最长不下降子序列中算法二中
元素小于 $d_len$ 这种情况的描述是这样的：
> 找到 第一个 大于它的元素，插入进去，丢弃在它之后的全部元素。
而原文链接中的描述是：
> 准确的说，并不是接在谁后面。而是替换掉谁。
这时候，我们需要保留后面的元素，因为可能会在后面被使用到。
而且范例代码中也是在替换元素而不是丢弃之后的元素。
=> fix(dp/basic.md): 修正最长不下降子序列中算法描述错误

docs/lang/java-pro.md
=> fix(java-pro.md)：修正 java 快读一节中 next 函数逻辑错误

docs/math/number-theory/prime.md
这里的 `for s in range(t)` 估计是直接从 C++ `for(s = 0; s < t; ++s)` 改过来的，有严重的问题。python 中 `s` 在任何情况下都不可能增大到 `t` ，使得紧随其后的 `if s == t` 判断形同虚设。
=> fix(prime.md): 更正了 Miller-Rabin 算法 python 代码实现中的错误

docs/string/sa.md
"若排名都不相同可直接生成后缀数组"：示例代码中 p == n 时再次把 sa 重新按照 rk 生成了一遍，给人一种“后缀数组还没有搞完” 的错觉，实际上这句话冗余了，删去不影响结果，测试结果：https://loj.ac/s/1802384
=> fix(sa.md): 删除 SA 示例中的冗余代码

docs/intro/format.md
`different` is too difficult to be recognized as a multi-letter variable, making this example hard to understand. This commit replace it with `size`, which is easier to be recognized as multi-letter variable.
=> fix(intro/format.md): adjust example for multi-letter variable

docs/ds/sparse-table.md
对于每个询问 $[l,r]$，我们把它分成两部分：$f(l,l+2^s-1)$ 与 $f(r-2^s+1,r)$，其中 $s=\left\lfloor\log_2(r-l+1)\right\rfloor$。两部分的结果的最大值就是回答。
应该为
对于每个询问 $[l,r]$，我们把它分成两部分：$[l,l+2^s-1]$ 与 $[r-2^s+1,r]$，其中 $s=\left\lfloor\log_2(r-l+1)\right\rfloor$。两部分的结果的最大值就是回答。
=> fix(ds/sparse-table.md): ST表查询错误

docs/lang/python.md
USTC 已经移除 PyPI 镜像四年半了。
参见：[PyPI 镜像变更通知](https://servers.ustclug.org/2019/01/pypi-%e9%95%9c%e5%83%8f%e5%8f%98%e6%9b%b4%e9%80%9a%e7%9f%a5/)
=> fix(lang/python.md): remove the link to USTC PyPI mirror

docs/string/code/suffix-bst/suffix-bst_2.cpp
主要修正了sgt的remove()函数，修改点有两处：
1. 在有孩子是空的情况下，使用孩子替代自己后进行rebuild。
这是因为此时孩子内的tag都不合法了，所以使用rebuild重新给它们的tag赋值。
这时直接进行rebuild是常数代价的，因为有一个孩子为空，这个子树的大小（包括被remove的节点） $n$ 有上限：
$$\alpha n \geq n - 1 \implies n \leq 1/(1-\alpha).$$
2. 在两个孩子均非空的情况下，使用一般二叉平衡树的删除方法，用左子树的最大值代替它，然后将它删除。
closes #4979 
closes #4985
=> fix(string/suffix-bst): fix remove() for sgt

docs/lang/pointer.md
修了一处 typo：`typdef` -> `typedef`。
=> fix(lang/pointer.md): 修了一处 typo，typedef 打错了

.github/workflows/build.yml, scripts/netlify/build.sh, scripts/post-build/external-links/task-handler.ts, scripts/post-build/html-postprocess.ts
For external links (absolute link to domains rather than "oi-wiki.org") without a `target` attribute, set their `target` to `"_blank"`.
=> feat: add target="_blank" to external links via html-postprocess

docs/graph/shortest-path.md
原代码中u取的是队首元素，但是pop删除的是队尾元素
因为Python的list中append和pop只能在队尾操作，所以一般使用标准库collections中deque类（原理为双向链表）来实现队列。
=> fix(shortest-path.md): SPFA python implementation

docs/string/code/suffix-bst/suffix-bst_1.cpp
例二的`remove()`已经在 #5083 中修过了，但例一里的版本还是错的。例一本来就不需要这个函数，直接删掉例一里的这个函数最省事、也最节省维护的人力成本。
=> fix(string/suffix-bst): remove wrong and unused `remove()` in the first example

docs/ds/code/monotonous-queue/monotonous-queue_1.cpp
原代码尽管可以得到正确的结果，但是有点奇怪。
队列指针初始化是有点问题的，按照该代码逻辑，`tail`指向为队列最后一个元素，`head`指向队列第一个元素，在这样的设定下，`tail`指向`head-1`处才表示空队列，但原代码并没有这样初始化。
原代码没有出bug的原因在于，一个没有初始化的全局数组默认初始化为全`0`值，那么对于第一次调用`get_min()`来说，由于`a`和`q`都被初始化为全`0`，那么
1. 对于`a[1]`，其必定要和`a[0]`对比，但`a[0]`本身并无意义，这样的比较也没有意义。
2. 如果`a`数组在第一个k大小的窗口内没有`<= 0`的值，则在处理完第一个窗口的值时，`q[0]`仍旧为0。在通过`q[head]`得到第一个窗口的最小值前，由于`q[0] <= i - k`，从而使得`head++`跳过了这个错误值。而由于`q[0]`仍旧为0，所以对于下一次调用`get_max()`，则如同本次调用`get_min()`一样，面临与本次调用`get_min()`相同的情况。
3. 如果`a`数组在第一个k大小的窗口内存在`<= 0`的值，那么对于第一个`<=0`的值`a[i]`，会让`tail--`，从而使得`tail=-1`，相当于做了一个初始化，该队列后续行为恰好符合一个从0开始的队列的形式，从而并没有问题。但它修改了`q[0]`的值，使得其并不为0，但对应的`a[q[0]]`必定`<=`第一个k大小窗口内的最小值，那么在调用`get_max()`时，在第一个k大小窗口内必定存在`a[i] >= a[q[0]]`从而使得`tail--`，此时又做了一次初始化，从而使得该队列后续表现正常。
综上：该代码可以得到一个正确的结果，但运行起来的方式有点奇怪，希望可以做一些调整，对队列的首尾指针做一个恰当的初始化。
=> fix(ds/monotonous-queue)  正确初始化队列首尾指针指向

docs/graph/save.md
直接存边中，刚开始初始化时，保存边的数组是从`0`开始的，后面遍历时是从`1`开始的。修正了该部分的bug。
=> fix(graph/save): 修正图存储中直接存边的bug

.github/workflows/build-pdf.yml, .github/workflows/incrementally-build-pdf.yml
参考：https://github.com/OI-wiki/OI-Wiki-export/pull/51
看起来是由于以前的 actions 有 bug，导致 `.npm` 文件夹中有文件权限为 `root`，现在这个 bug 被修复了，但利用以前的 cache 的时候会出现权限不足的问题。
=> fix(ci/pdf): 修复工作流 LaTeX 文档构建失败的问题

mkdocs.yml
`content.action.edit` became an optional feature in material-mkdocs 9.0
=> fix(mkdocs.yml): edit button missing

docs/basic/binary.md
在while循环中，mid的赋值应该取决于上次循环已经进行修改了的l和r，而不是lmid和rmid(使用lmid和rmid会陷入死循环)
=> fix(binary.md): 三分法实现中c++代码有误

docs/dp/opt/quadrangle.md
区间合并 部分引理一证明中有误：
根据下文 $f(a,d) + f(b,c) \geq f(a,d) + f(b,c)$ 应当是 $f(a,d) + f(b,c) \geq f(a,c) + f(b,d)$
~~（$f(a,d) + f(b,c) \geq f(a,d) + f(b,c)$ 好像也可以不用证明吧）~~
=> fix (dp/opt/quadrangle.md) fix typo

docs/graph/matrix-tree.md
性质1（Laplace 矩阵所有代数余子式的值都相等）中证明中有一处笔误，交换两列移动第 k 到第 j 列，所以对符号的影响应该是 (-1)^{1+(k-1)-(**j**+1)+1} 而不是 (-1)^{1+(k-1)-(**r**+1)+1}。
=> fix(graph/matrix-tree): 修正笔误

docs/math/number-theory/primitive-root.md
=> fix(primitive-root.md): 证明时的性质使用序号错误，是基于性质3而不是性质1

docs/geometry/convex-hull.md
fix #5424
栈顶指针tp递增位置应位于入栈(stk[tp] = i)之前；
标记当前元素i在凸壳上、将i入栈的这三行代码应位于while循环之外（缩进问题）
=> fix(geometry/convex-hull.md): Andrew算法的python代码

docs/contest/common-mistakes.md
在“会导致未知的结果”一节中增加“尝试释放由 `new []` 分配的整块内存的一部分“相关内容
=> feat(contest/common-mistakes.md): 在“会导致未知的结果”一节中增加“尝试释放由 `new []` 分配的整块内存的一部分“相关内容

docs/math/poly/fft.md
修复快速傅里叶变换线性算子，原文中的 $\alpha$ 与矩阵的形式不符
=> fix(fft.md): typo

docs/ds/leftist-tree.md
=> fix(ds/leftist-tree.md): 修改左偏树任意节点删除操作

docs/ds/leftist-tree.md
#5609 中在 `dist` 维护时也用的是 `rs_ref`，但是通过调试应该再取一遍 `rs(x)`，保证维护的是真的右节点。
不过使用 `rs_ref` 也没有超时，保险起见使用 `rs(x)`，与其他样例代码维护 `dist` 的行为保持一致。
=> fix(ds/leftist-tree.md): fix potential wrong dist maintain

docs/dp/knapsack.md
<feat>(<doc/dp/knapsack.md>): <多重背包非二进制优化代码>
<feat>(<doc/dp/knapsack.md>): <分组背包参考代码>
=> feat(dp/knapsack.md): 完善背包问题参考代码

docs/contest/common-mistakes.md
在[常见错误](https://oi-wiki.org/contest/common-mistakes/)中，存在如下内容
> 因为编译器可以假定有符号整数永远不会溢出，因此 `x > x + 1` 恒成立。
但参考上下文，发现这里 `x > x + 1`在不溢出的情况下，不会成立，因此作出修改
=> fix(common-mistakes.md): typo

docs/math/number-theory/gcd.md
原 Stein 算法代码实现中最后结果计算使用了更新后的 btimes ，这使得最终结果与正确结果缺少 2 的若干个次方，因此将Stein 算法代码实现中取最小值提前，以确保 btimes 的更新不会影响到最终答案。
=> fix(math/number-theory/gcd): 修改 Stein 算法实现代码的错误

docs/contest/common-mistakes.md
删去了“特别的，也不能在执行 ios::sync_with_stdio(false); 后使用 freopen。”。这并没有理论依据，且很可能是无中生有的说法。
=> fix(docs/contest/common-mistakes.md): 删去一个错项

docs/tools/special-judge.md
修改了部分事实性错误：
- LibreOJ 现基于 Lyrio 而并非 SYZOJ。
- 根据 [SYZOJ judge-v3 源代码](https://github.com/syzoj/judge-v3/blob/a8c7fcfac628084225cef6670bfcc4f5429fa336/src/runner/judge.ts#L89)，SYZOJ 2 的输入文件为 input 而非 in。
=> fix(tools/special-judge.md): Correct factual errors regarding SYZOJ 2

.github/workflows/update-feedback-sys-meta.yml, scripts/update-feedback-sys-meta.py
此 pr 提供 feedback-sys 在源文档发生更改时对评论位置数据的动态修正能力。该 pr 增加的功能如下：
- 新增了一个 github workflow，旨在有新的主线 push 侦测 docs/ 目录下的文件更改，并收集这些信息
- 将上述数据传递给 `scripts/update-feedback-sys-meta.py`，该文件会计算更改，然后将计算结果传递给 workers 后端，由后端进行进一步分析并进行修改
- 对于文件重命名，也会遵循上述方案，来自动更改后端存储的相关数据
查看 https://github.com/OI-wiki/feedback-sys/pull/27 可以获得有关该功能的更多信息。
=> feat: feedback-sys commit offsets patch

scripts/update-feedback-sys-meta.py
此 PR 修复了一个 bug，导致 update feedback-sys meta 脚本运行失败，以及未能正确 encode path 的问题
=> fix: path encoding in update feedback-sys meta

docs/ds/bst.md
原有remove()示例代码缺少对节点的size的更新，导致发生删除后size与子树元素数目不一致，添加对size更新
=> fix(bst.md): BST remove操作示例代码添加对节点size更新操作

docs/math/combinatorics/fibonacci.md, docs/math/number-theory/lift-the-exponent.md, docs/math/number-theory/wilson.md
统一记号 $\nu_p(n)$ 而不是 $v_p(n)$。
参考：https://en.wikipedia.org/wiki/P-adic_valuation
=> fix(math): unify the notation of p-adic valuations

docs/math/number-theory/primitive-root.md
=> feat(primitive-root.md): 使证明自然一点

docs/math/number-theory/powerful-number.md
把例题 1 Min_25 筛 中杜教筛的公式中第二个求和号的下标 $i$ 修正为 $d$。
fixed #6121
修改了 powerful-number.md 一个文件，在例题 1 一节中杜教筛的公式内，第二个求和号的下标使用了 $i$，但紧随其后的内容中使用了 $d$，故修改了这一处问题。
=> fix(math/number-theory/powerful-number.md): 例题杜教筛公式中求和下标有误并加以修正

docs/ds/bplus-tree.md
在B+树removeInternal中，当左右兄弟都不够借用时，需要进行合并。在合并时，拷贝数据出现问题，i未++导致数据拷贝至同一位置。代码位于403行至420行。
issue:https://github.com/OI-wiki/OI-wiki/issues/6166#issue-2931891047
=> fix(bplus-tree.md): B+删除代码部分，在进行合并节点时，拷贝有误 (#6166)

.github/workflows/check-characters.yml
> 可以看一下这个 failed 的 actions 吗，似乎是和 `tj-actions/changed-files` 相关的。
> 我搜索了一下，只有这个 actions 在 checkout 的时候没有加 `fetch-depth: 0`，是否和这个问题有关。`actions/checkout` 对这一项的描述是：
> ```yaml
>     # Number of commits to fetch. 0 indicates all history for all branches and tags.
>     # Default: 1
>     fetch-depth: ''
> ```
> _最初由 @HeRaNO 在 https://github.com/OI-wiki/OI-wiki/pull/6174#issuecomment-2750314457 发布_
在使用 `tj-actions/changed-files` 并开启 `since_last_remote_commit` 时，设置 `fetch-depth` 为 `1` 并不总能满足需求，尽管在 `tj-actions/changed-files` 的 README 中并没有进行任何强调或暗示。
但实际上，Checkout 正在检查 PR HEAD 和基本分支的合并，`fetch-depth` 在这种情况下不能达到预期效果。具体相关问题可参考 actions/checkout#881 。
虽然直接获取完整 git 记录（设置 `fetch-depth` 为 `0`）是一种可行的解决方案，本 PR 设置其为 `2` 并将 `sha` 设置为 `${{ github.event.pull_request.head.sha }}`，以达到最高的运行效率。
ref: …
=> fix(check-characters.yml): 设置 `fetch-depth` 避免 git 记录不完整

docs/dp/number.md
直接复制粘贴跑一遍是会报错的，因为pre函数是int类型，但是并没有返回值，改成void就好了
=> fix(dp/number.md): 例题2代码的pre函数类型改为void

docs/contest/oi.md
依据CCF于2025年2月13日发布的在[《关于参加CSP-J/S认证需符合年龄条件的公告》](https://www.noi.cn/xw/2025-02-13/837984.shtml)将CSP-J/S报名年龄限制进行相应修改。
=> fix(contest/oi.md): 修改CSP年龄限制 (#6213)

docs/ds/bst.md
修改查找排名为 k 的元素代码中错误部分。
这里当```if(root->left)```不满足的时候，若```root->count```为5，而```k```为4时，理应返回```root->key```。
所以```k == 1```应当改为```k <= root->count```。
=> fix(ds/bst.md): 修改有关错误代码

docs/lang/python.md
Python 速成页面，【文件读写】版块目前被放在【控制流程】下。感觉不合适，应该移至【输入输出】下。
=> fix(lang/python): 移动【文件读写】模块

scripts/post-build/math/task-handler.ts
To improve a11y and make visitors can control math style if they want.
Recommend to read "Is MathML accessible?"[^1] by Peter Krautzberger (who is the maintainer of MathJax and participated in the research and development of many mathematics-related Web standards.), Presentation MathML is not the prefect solution of math accessibility, but it's the best one we have, and many people are working on improving it. Content MathML is better for a11y, but a well-written Presentation MathML can reach the same level as well, and Content MathML support is really really poor, especially in browsers (Maybe zero, I think.). MathJax exactly is the right tool to get well-written Presentation MathML.
For later usage, please use Native MathML extension[^2][^3], or use CSS below:
```css
/* …
```
=> feat(scripts/post-build/math): add MathJax MathML output back

docs/contest/resources.md
fix(contest/resources): 把codeforces网友资源合集链接改成另一个博客，原链接是它的子集
把它修改成了我之前做的博客。参考了原链接，codeforces catalog，以及好几篇其他的类似的资源合集博客，分类也比原来的更详细，内容也多得多，希望能通过这个帮助更多同学。
=> fix(contest/resources): 把codeforces网友资源合集链接改成另一个博客，原链接是它的子集

.github/workflows/lint_pr_title.yml, .github/workflows/remove-labels.yml
为使工作流获得与 PR 交互所需的写入权限，此修改将 `lint_pr_title.yml` 和 `remove_labels.yml` 两个工作流的触发事件从 `pull_request` 更改为 `pull_request_target`。
出于安全性考量，GitHub 为工作流触发提供了 `pull_request` 和 `pull_request_target` 事件。原使用的 `pull_request` 事件触发的工作流只能获得权限受限的 `GITHUB_TOKEN`，无法向部分 PR 写入数据；而 `on: pull_request_target` 的工作流则拥有写入权限，从而才能成功执行评论和修改标签等操作。
此修改符合 GitHub Actions 使用习惯，如 `actions/github-script` 的 README 示例 Welcome a first-time contributor 明确需使用 `on: pull_request_target`。
此修改调整的工作流均具有较高安全性，主要得益于以下两点：
1. 无代码检出与执行风险：工作流均未执行 Checkout 步骤，完全不拉取 PR 中的代码，从根本上避免潜在恶意代码在基仓库的信任环境中执行的风险。
2. 最小安全信息访问：工作流仅直接或间接通过 GitHub 官方提供的交互库读取 PR 元数据，未主动获取其它数据。
=> fix(lint_pr_title.yml, remove_labels.yml): 通过 `pull_request_target` 触发需交互 PR 的工作流

docs/edit-landing.md
=> fix(edit-landing.md): use spaces instead of tabs

docs/graph/graph-matching/bigraph-match.md
对于例题中的Gym 104427B Lawyers，可以描述为(a,b)这个无序对只能从a和b中选一个辩护，因此对于信任关系(a,b)，应当建立的是无序对(a,b)到b的边，而不是到a。在cf上提交后，发现建立(a,b)到b的边可ac，建立(a,b)到a的边wa。
=> fix(graph/graph-matching/bigraph-match.md): 修改例题解法中的建边错误
